#!/usr/bin/env python3
# Copyright 2024-2026 Lager Data
# SPDX-License-Identifier: Apache-2.0
"""Unit tests for ``PythonServiceHandler.parse_multipart``.

This is the box's file-upload path -- everything ``lager python`` and
``lager binaries add`` send arrives through it. It had no coverage at all,
which is uncomfortable given it was just rewritten off ``cgi.FieldStorage``
(PEP 594 removed ``cgi`` in 3.13, so the module would not import there).

The contract under test is the return SHAPE, because downstream code branches
on all three forms:

    repeated name (args, env)      -> list of bytes
    filename ends .py / .zip       -> io.BytesIO
    anything else                  -> bytes

The load-bearing case is the last one. ``cli/commands/development/python.py``
posts the module zip as ``('module', zipped_folder)`` with **no filename
tuple**, so it arrives as a non-file part carrying raw binary. Werkzeug's
high-level ``parse_form_data()`` decodes non-file parts as text: measured on a
1024-byte binary payload it returned a str with 512 bytes replaced by U+FFFD
and raised nothing. ``test_werkzeug_high_level_api_would_corrupt_the_module``
pins that as the reason the sansio decoder is used, so nobody "simplifies" it
back.

Bodies are generated by ``requests`` itself rather than hand-written, so these
exercise the real client's framing (its boundary, its header casing, its CRLFs)
instead of a guess at it.
"""

import io
import unittest

import requests

from lager.python.service import PythonServiceHandler


def encode(fields):
    """Build a real multipart body with requests' own encoder.

    `fields` is a list of (name, value) where value is either bytes (a plain
    part, no filename) or a (filename, bytes) tuple (a file part) -- mirroring
    how cli/commands/development/python.py builds post_data.
    """
    files = []
    for name, value in fields:
        if isinstance(value, tuple):
            filename, data = value
            files.append((name, (filename, data, 'application/octet-stream')))
        else:
            files.append((name, (None, value)))
    body, content_type = requests.models.RequestEncodingMixin._encode_files(files, {})
    return body, content_type


class FakeRfile:
    """Records how many bytes the handler asked for."""

    def __init__(self, body):
        self._buf = io.BytesIO(body)
        self.read_sizes = []

    def read(self, size=-1):
        self.read_sizes.append(size)
        return self._buf.read(size)


def parse(fields, *, truncate_content_length=None, content_type=None):
    """Run parse_multipart over a body built from `fields`."""
    body, ctype = encode(fields)
    handler = PythonServiceHandler.__new__(PythonServiceHandler)
    handler.headers = {
        'Content-Type': content_type or ctype,
        'Content-Length': str(truncate_content_length
                              if truncate_content_length is not None else len(body)),
    }
    handler.rfile = FakeRfile(body)
    return handler.parse_multipart(), handler


class FieldShapeTests(unittest.TestCase):
    """The three return forms downstream code depends on."""

    def test_plain_field_is_bytes(self):
        fields, _ = parse([('detach', b'false')])
        self.assertEqual(fields['detach'], b'false')
        self.assertIsInstance(fields['detach'], bytes)

    def test_py_upload_becomes_bytesio(self):
        fields, _ = parse([('script', ('run.py', b'print(1)'))])
        self.assertIsInstance(fields['script'], io.BytesIO)
        self.assertEqual(fields['script'].read(), b'print(1)')

    def test_zip_upload_becomes_bytesio(self):
        fields, _ = parse([('module', ('bundle.zip', b'PK\x03\x04payload'))])
        self.assertIsInstance(fields['module'], io.BytesIO)
        self.assertEqual(fields['module'].read(), b'PK\x03\x04payload')

    def test_repeated_name_becomes_a_list_of_bytes(self):
        fields, _ = parse([('args', b'one'), ('args', b'two'), ('args', b'three')])
        self.assertEqual(fields['args'], [b'one', b'two', b'three'])

    def test_repeated_names_keep_their_order(self):
        fields, _ = parse([('env', b'A=1'), ('env', b'B=2')])
        self.assertEqual(fields['env'], [b'A=1', b'B=2'])

    def test_single_repeat_capable_field_is_not_wrapped_in_a_list(self):
        """One `args` is bytes, not [bytes] -- the caller re-wraps it."""
        fields, _ = parse([('args', b'only')])
        self.assertEqual(fields['args'], b'only')

    def test_file_with_a_non_upload_suffix_stays_bytes(self):
        """Suffix decides, not the presence of a filename."""
        fields, _ = parse([('binary', ('tool.bin', b'\x7fELF'))])
        self.assertEqual(fields['binary'], b'\x7fELF')

    def test_filename_without_a_suffix_stays_bytes(self):
        fields, _ = parse([('binary', ('mytool', b'\x7fELF'))])
        self.assertEqual(fields['binary'], b'\x7fELF')


class BinaryFidelityTests(unittest.TestCase):
    """The reason this parser is not werkzeug.formparser."""

    BINARY = bytes(range(256)) * 8   # every byte value, invalid UTF-8

    def test_filenameless_binary_field_survives_byte_for_byte(self):
        """The `module` field: raw zip, posted with no filename."""
        fields, _ = parse([('module', self.BINARY)])
        self.assertEqual(fields['module'], self.BINARY)

    def test_zip_upload_survives_byte_for_byte(self):
        fields, _ = parse([('module', ('m.zip', self.BINARY))])
        self.assertEqual(fields['module'].read(), self.BINARY)

    def test_binary_upload_survives_byte_for_byte(self):
        """`lager binaries add` -- an ELF, no .py/.zip suffix."""
        fields, _ = parse([('binary', ('tool', self.BINARY))])
        self.assertEqual(fields['binary'], self.BINARY)

    def test_crlf_inside_a_payload_is_not_treated_as_a_delimiter(self):
        payload = b'line1\r\nline2\r\n--notaboundary\r\n'
        fields, _ = parse([('module', payload)])
        self.assertEqual(fields['module'], payload)

    def test_payload_containing_the_boundary_text(self):
        body, ctype = encode([('module', b'x')])
        boundary = PythonServiceHandler._boundary_from(ctype)
        fields, _ = parse([('module', b'prefix' + boundary + b'suffix')])
        self.assertEqual(fields['module'], b'prefix' + boundary + b'suffix')

    def test_empty_payload(self):
        fields, _ = parse([('module', b'')])
        self.assertEqual(fields['module'], b'')

    def test_large_payload_spanning_many_chunks(self):
        big = bytes(range(256)) * 4096   # 1 MiB
        fields, _ = parse([('module', big)])
        self.assertEqual(fields['module'], big)

    def test_werkzeug_high_level_api_would_corrupt_the_module(self):
        """Pins WHY the sansio decoder is used. Delete only with a replacement.

        werkzeug.formparser.parse_form_data decodes non-file parts as text, so
        the filenameless binary `module` field comes back as a lossy str. It
        raises nothing -- the corruption is silent, which is what makes it
        dangerous. If a future werkzeug makes this lossless, this test fails
        and the simpler API becomes available; that is a good failure.
        """
        from werkzeug.formparser import parse_form_data

        body, ctype = encode([('module', self.BINARY)])
        environ = {
            'REQUEST_METHOD': 'POST',
            'CONTENT_TYPE': ctype,
            'CONTENT_LENGTH': str(len(body)),
            'wsgi.input': io.BytesIO(body),
        }
        _stream, form, files = parse_form_data(environ, max_form_memory_size=10 * 1024 * 1024)

        self.assertNotIn('module', files, 'filenameless part is not treated as a file')
        self.assertIsInstance(form['module'], str)
        self.assertNotEqual(form['module'].encode('utf-8', 'surrogateescape'), self.BINARY)
        self.assertIn('�', form['module'], 'expected lossy replacement characters')

        # And the parser actually in use gets it exactly right.
        fields, _ = parse([('module', self.BINARY)])
        self.assertEqual(fields['module'], self.BINARY)


class RequestFramingTests(unittest.TestCase):

    def test_reads_exactly_content_length(self):
        """Not read-to-EOF: the connection is keep-alive and would block."""
        body, _ = encode([('detach', b'false')])
        _fields, handler = parse([('detach', b'false')])
        self.assertEqual(handler.rfile.read_sizes, [len(body)])

    def test_non_multipart_content_type_returns_empty(self):
        handler = PythonServiceHandler.__new__(PythonServiceHandler)
        handler.headers = {'Content-Type': 'application/json', 'Content-Length': '2'}
        handler.rfile = FakeRfile(b'{}')
        self.assertEqual(handler.parse_multipart(), {})

    def test_missing_content_type_returns_empty(self):
        handler = PythonServiceHandler.__new__(PythonServiceHandler)
        handler.headers = {}
        handler.rfile = FakeRfile(b'')
        self.assertEqual(handler.parse_multipart(), {})

    def test_multipart_without_a_boundary_returns_empty(self):
        """Malformed header must not raise out of the handler."""
        handler = PythonServiceHandler.__new__(PythonServiceHandler)
        handler.headers = {'Content-Type': 'multipart/form-data', 'Content-Length': '0'}
        handler.rfile = FakeRfile(b'')
        self.assertEqual(handler.parse_multipart(), {})

    def test_zero_content_length_returns_empty(self):
        fields, _ = parse([('detach', b'false')], truncate_content_length=0)
        self.assertEqual(fields, {})

    def test_quoted_boundary_is_accepted(self):
        """RFC 2046 permits a quoted boundary; the header parser must strip it.

        Built from ONE body: encode() picks a fresh random boundary per call,
        so quoting the boundary of one body and parsing a different one tests
        nothing but a mismatch.
        """
        body, ctype = encode([('detach', b'true')])
        boundary = PythonServiceHandler._boundary_from(ctype).decode()
        handler = PythonServiceHandler.__new__(PythonServiceHandler)
        handler.headers = {
            'Content-Type': f'multipart/form-data; boundary="{boundary}"',
            'Content-Length': str(len(body)),
        }
        handler.rfile = FakeRfile(body)
        self.assertEqual(handler.parse_multipart()['detach'], b'true')

    def test_boundary_extraction(self):
        self.assertEqual(
            PythonServiceHandler._boundary_from('multipart/form-data; boundary=abc123'),
            b'abc123')
        self.assertEqual(
            PythonServiceHandler._boundary_from('multipart/form-data; boundary="a b"'),
            b'a b')
        self.assertEqual(
            PythonServiceHandler._boundary_from('multipart/form-data; charset=utf-8; boundary=x'),
            b'x')
        self.assertIsNone(
            PythonServiceHandler._boundary_from('multipart/form-data'))


class RealisticPayloadTests(unittest.TestCase):
    """The shapes the CLI actually sends, end to end."""

    def test_lager_python_script_invocation(self):
        fields, _ = parse([
            ('detach', b'false'),
            ('stdout_is_stderr', b'true'),
            ('timeout', b'300'),
            ('script', ('demo.py', b'print("hi")')),
            ('args', b'--fast'),
            ('args', b'--verbose'),
            ('env', b'FOO=bar'),
        ])
        self.assertEqual(fields['detach'], b'false')
        self.assertEqual(fields['timeout'], b'300')
        self.assertIsInstance(fields['script'], io.BytesIO)
        self.assertEqual(fields['args'], [b'--fast', b'--verbose'])
        self.assertEqual(fields['env'], b'FOO=bar')

    def test_lager_python_directory_invocation(self):
        """The module zip: binary, filenameless, and the corruption risk."""
        zip_bytes = b'PK\x03\x04' + bytes(range(256)) * 4
        fields, _ = parse([
            ('detach', b'false'),
            ('timeout', b'300'),
            ('module', zip_bytes),
        ])
        self.assertEqual(fields['module'], zip_bytes)

    def test_binaries_add_invocation(self):
        fields, _ = parse([
            ('binary', ('mytool', b'\x7fELF\x02\x01\x01')),
            ('name', b'mytool'),
        ])
        self.assertEqual(fields['binary'], b'\x7fELF\x02\x01\x01')
        self.assertEqual(fields['name'], b'mytool')


class DownstreamConsumerTests(unittest.TestCase):
    """The shapes must satisfy the code that reads them."""

    def test_is_truthy_string_accepts_what_parse_multipart_produces(self):
        from lager.python.service import is_truthy_string
        fields, _ = parse([('detach', b'true'), ('stdout_is_stderr', b'false')])
        self.assertTrue(is_truthy_string(fields['detach']))
        self.assertFalse(is_truthy_string(fields['stdout_is_stderr']))

    def test_timeout_field_converts_to_int(self):
        """_handle_python_execute decodes then int()s this."""
        fields, _ = parse([('timeout', b'300')])
        value = fields['timeout']
        self.assertEqual(int(value.decode() if isinstance(value, bytes) else value), 300)

    def test_bytes_module_hits_the_bytesio_rescue_path(self):
        """_handle_python_execute wraps a bytes `module` in BytesIO itself."""
        fields, _ = parse([('module', b'PK\x03\x04')])
        module_zip = fields['module']
        self.assertIsInstance(module_zip, bytes)
        self.assertEqual(io.BytesIO(module_zip).read(), b'PK\x03\x04')

    def test_cgi_is_no_longer_imported(self):
        """PEP 594 removed `cgi` in 3.13; importing it here breaks the box."""
        import lager.python.service as service
        self.assertFalse(hasattr(service, 'cgi'))
        source = open(service.__file__).read()
        self.assertNotIn('\nimport cgi', source)


if __name__ == '__main__':
    unittest.main()
