// Copyright 2024-2026 Lager Data
// SPDX-License-Identifier: Apache-2.0

//! Runtime loading of the PicoTech shared libraries.
//!
//! The drivers are opened with `dlopen` rather than linked, which is what
//! lets a single daemon binary drive whichever series is plugged in and lets
//! the crate build with no SDK installed.
//!
//! Each library is opened at most once and leaked for the process lifetime.
//! That is deliberate: unloading a PicoTech driver while a device handle is
//! open leaves the USB endpoint in a state that needs a physical replug, and
//! there is no point at which the daemon benefits from closing it.

use std::path::PathBuf;
use std::sync::OnceLock;

use anyhow::{Context, Result};

/// Directories to search, in order. The packaged location comes first so a
/// box with the PicoTech packages uses those rather than anything a
/// developer happens to have on the loader path.
const SEARCH_DIRS: &[&str] = &[
    "/opt/picoscope/lib",
    "/usr/local/lib",
    "/usr/lib/x86_64-linux-gnu",
    "/usr/lib/aarch64-linux-gnu",
    "/usr/lib",
];

/// Locate a driver by soname, returning the first existing candidate.
///
/// Both the bare soname and the `.1` suffixed form are tried: the PicoTech
/// packages install `libps2000.so.2` and only ship the unsuffixed symlink in
/// their `-dev` package, which boxes do not necessarily have.
pub fn find_library(soname: &str) -> Option<PathBuf> {
    let stem = soname.trim_end_matches(".so");
    let candidates = [
        soname.to_string(),
        format!("{stem}.so.2"),
        format!("{stem}.so.1"),
    ];

    for dir in SEARCH_DIRS {
        for candidate in &candidates {
            let path = PathBuf::from(dir).join(candidate);
            if path.exists() {
                return Some(path);
            }
        }
    }
    None
}

/// Which driver libraries are present on this machine.
pub fn installed_families() -> Vec<protocol::DriverFamily> {
    use protocol::DriverFamily::*;
    [Ps2000, Ps2000a, Ps3000a, Ps4000a, Ps5000a]
        .into_iter()
        .filter(|family| find_library(family.library_name()).is_some())
        .collect()
}

// Generated by build.rs from the vendored ps2000.h. `dynamic_library_name`
// makes bindgen emit a `Ps2000` struct whose methods dispatch through
// function pointers resolved at load time.
#[allow(
    non_camel_case_types,
    non_upper_case_globals,
    non_snake_case,
    dead_code,
    unused_imports,
    // bindgen's dynamic-library wrapper calls libloading::Library::get from
    // inside its own unsafe fns without an inner unsafe block. Edition 2024
    // warns on that and a future edition will reject it, but the code is
    // generated, so the lint is silenced here rather than patched in build.rs.
    unsafe_op_in_unsafe_fn
)]
// Same reasoning for clippy: these fire on bindgen's output, where the C
// signatures are what they are and the wrapper is not ours to restructure.
#[allow(
    clippy::type_complexity,
    clippy::missing_safety_doc,
    clippy::too_many_arguments
)]
pub mod ps2000_sys {
    include!(concat!(env!("OUT_DIR"), "/libps2000_bindings.rs"));
}

pub use ps2000_sys::Ps2000;

/// The four modern families, generated the same way as ps2000 above.
///
/// Each gets its own bindgen module because the headers declare their own
/// types; `modern.rs` puts one trait over the four so the rest of the
/// daemon does not see the difference.
macro_rules! sys_module {
    ($module:ident, $bindings:literal, $struct_name:ident) => {
        #[allow(
            non_camel_case_types,
            non_upper_case_globals,
            non_snake_case,
            dead_code,
            unused_imports,
            // See the note on ps2000_sys: bindgen's dynamic-library wrapper
            // calls libloading from inside its own unsafe fns without an
            // inner unsafe block, which edition 2024 warns about. The code
            // is generated, so the lint is silenced rather than patched.
            unsafe_op_in_unsafe_fn
        )]
        // Same reasoning for clippy: these fire on bindgen's output, where
        // the C signatures are what they are and the wrapper is not ours to
        // restructure. Left on for hand-written code elsewhere.
        #[allow(
    clippy::type_complexity,
    clippy::missing_safety_doc,
    clippy::too_many_arguments
)]
        pub mod $module {
            include!(concat!(env!("OUT_DIR"), "/", $bindings));
        }
        pub use $module::$struct_name;
    };
}

sys_module!(ps2000a_sys, "libps2000a_bindings.rs", Ps2000a);
sys_module!(ps3000a_sys, "libps3000a_bindings.rs", Ps3000a);
sys_module!(ps4000a_sys, "libps4000a_bindings.rs", Ps4000a);
sys_module!(ps5000a_sys, "libps5000a_bindings.rs", Ps5000a);

/// Define a `OnceLock`-backed accessor that dlopens a driver on first use.
///
/// Returns an error rather than panicking when the library is absent, so a
/// box without a given series' package reports a clear message instead of
/// aborting the daemon. The failure is cached too: a missing driver should
/// not mean a filesystem walk on every request.
macro_rules! driver_accessor {
    ($fn_name:ident, $struct_name:ty, $soname:literal, $cell:ident) => {
        static $cell: OnceLock<Result<&'static $struct_name, String>> = OnceLock::new();

        #[doc = concat!("The loaded `", $soname, "` driver.")]
        pub fn $fn_name() -> Result<&'static $struct_name> {
            $cell
                .get_or_init(|| {
                    let path = find_library($soname).ok_or_else(|| {
                        format!(
                            "{} not found in {}. Install the PicoScope SDK \
                             (lager install does this) or set LD_LIBRARY_PATH.",
                            $soname,
                            SEARCH_DIRS.join(", ")
                        )
                    })?;

                    // Safety: loading a shared library runs its
                    // initialisers. These are PicoTech's own drivers from a
                    // trusted package.
                    let library = unsafe { <$struct_name>::new(&path) }
                        .map_err(|e| format!("could not load {}: {e}", path.display()))?;

                    tracing::info!(
                        path = %path.display(),
                        driver = $soname,
                        "loaded PicoScope driver"
                    );

                    // Leaked intentionally: see the module docs.
                    Ok(&*Box::leak(Box::new(library)))
                })
                .as_ref()
                .copied()
                .map_err(|e| anyhow::anyhow!(e.clone()))
                .with_context(|| format!("{} driver unavailable", $soname))
        }
    };
}

driver_accessor!(ps2000, Ps2000, "libps2000.so", PS2000);
driver_accessor!(ps2000a, Ps2000a, "libps2000a.so", PS2000A);
driver_accessor!(ps3000a, Ps3000a, "libps3000a.so", PS3000A);
driver_accessor!(ps4000a, Ps4000a, "libps4000a.so", PS4000A);
driver_accessor!(ps5000a, Ps5000a, "libps5000a.so", PS5000A);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn library_search_covers_the_packaged_location() {
        assert!(SEARCH_DIRS.contains(&"/opt/picoscope/lib"));
    }

    #[test]
    fn missing_library_is_an_error_not_a_panic() {
        // Nothing installs this, so the lookup must simply come back empty.
        assert!(find_library("libps_does_not_exist.so").is_none());
    }
}
