#!/usr/bin/env python3
# Copyright 2024-2026 Lager Data
# SPDX-License-Identifier: Apache-2.0
"""
Unit tests for `lager box update`'s box-state probe — specifically the
0.20.0 additions that detect the modprobe.d/blacklist-usbtmc.conf state
and the usbtmc kernel module load state.

The probe itself is a shell script that runs over SSH; we don't try to
spin up SSH here. Instead we verify two things:
  1. The probe script string emits the new LAGER_PROBE_MODPROBE_* and
     LAGER_PROBE_USBTMC_LOADED keys (regression guard against someone
     deleting the new lines).
  2. `_parse_probe_output` correctly extracts those keys into the facts
     dict so the deploy path reads them as expected.
"""

import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))))

from cli.commands.utility.update import _probe_shell_script, _parse_probe_output


class ProbeScriptEmitsModprobeKeys(unittest.TestCase):
    """Smoke test: the probe shell script generated by `_probe_shell_script`
    must contain the new key names. If someone refactors the script and
    accidentally drops these, update.py's status print + Step 5b silently
    fall into the SKIPPED branch and the blacklist never deploys."""

    def setUp(self):
        self.script = _probe_shell_script()

    def test_modprobe_src_path_key_present(self):
        self.assertIn('LAGER_PROBE_MODPROBE_SRC_PATH=', self.script)

    def test_modprobe_src_confs_key_present(self):
        self.assertIn('LAGER_PROBE_MODPROBE_SRC_CONFS=', self.script)

    def test_modprobe_in_sync_key_present(self):
        self.assertIn('LAGER_PROBE_MODPROBE_IN_SYNC=', self.script)

    def test_usbtmc_loaded_key_present(self):
        self.assertIn('LAGER_PROBE_USBTMC_LOADED=', self.script)

    def test_probe_checks_box_modprobe_d_dir(self):
        """Probe must look for the source dir under ~/box/modprobe_d (or the
        sparse-checkout-pre-flatten ~/box/box/modprobe_d). If only one is
        checked, freshly-cloned boxes will report `source dir missing`."""
        self.assertIn('~/box/modprobe_d', self.script)
        self.assertIn('~/box/box/modprobe_d', self.script)

    def test_probe_checks_specific_blacklist_file(self):
        self.assertIn('blacklist-usbtmc.conf', self.script)


class ParseProbeOutputHandlesModprobeKeys(unittest.TestCase):
    """`_parse_probe_output` is generic over LAGER_PROBE_* keys, but we
    pin the contract here so the calling code can rely on these specific
    fact-dict entries showing up post-parse."""

    def test_parses_modprobe_keys_into_facts(self):
        stdout = '\n'.join([
            'some unrelated motd line',
            'LAGER_PROBE_MODPROBE_SRC_PATH=/home/lagerdata/box/modprobe_d',
            'LAGER_PROBE_MODPROBE_SRC_CONFS=1',
            'LAGER_PROBE_MODPROBE_IN_SYNC=0',
            'LAGER_PROBE_USBTMC_LOADED=1',
            'LAGER_PROBE_ETC_VERSION=0.19.2',
        ])
        facts = _parse_probe_output(stdout)
        self.assertEqual(facts['MODPROBE_SRC_PATH'], '/home/lagerdata/box/modprobe_d')
        self.assertEqual(facts['MODPROBE_SRC_CONFS'], '1')
        self.assertEqual(facts['MODPROBE_IN_SYNC'], '0')
        self.assertEqual(facts['USBTMC_LOADED'], '1')
        # Sanity: pre-existing keys still parse.
        self.assertEqual(facts['ETC_VERSION'], '0.19.2')

    def test_missing_modprobe_keys_default_to_absent(self):
        """If a box is on a pre-0.20 image, the probe won't emit the new
        keys. Callers read them with .get(key, '') and treat absent as the
        'source dir missing (older box code)' status."""
        stdout = 'LAGER_PROBE_ETC_VERSION=0.18.5'
        facts = _parse_probe_output(stdout)
        self.assertNotIn('MODPROBE_SRC_PATH', facts)
        self.assertNotIn('USBTMC_LOADED', facts)
        self.assertEqual(facts.get('MODPROBE_SRC_PATH', ''), '')


if __name__ == '__main__':
    unittest.main()
