#!/usr/bin/env python3
# Copyright 2024-2026 Lager Data
# SPDX-License-Identifier: Apache-2.0
"""
Unit tests for `lager update`'s secret-file ownership repair.

Like the flatten and build-hash snippets next door, this is shell that normally
runs over SSH, generated by a plain function — so each test runs the real
shipped string through `bash` against a throwaway directory, with a fake `sudo`
on PATH that records what would have run without invoking the real one.

Why the repair exists: mode 0600 grants the OWNER alone, and everything that
reads these files runs as uid 33 in the container. A secrets file copied onto a
box by hand belongs to whoever copied it; the boot script then tightens it to
0600 — successfully, because that user owns it — and the runtime can no longer
read its own secrets. Nothing fails loudly, since secret injection just returns
an empty dict. `lager update` is the one path that runs with real privilege, so
it is where the repair belongs.

The chown itself is not reproducible in a unit test (changing a file's owner
needs privilege). What is pinned here is the shape of the command, that it only
touches files that exist, and that it can never fail an update.
"""

import os
import shlex
import shutil
import subprocess
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))))

from cli.commands.utility.update import (  # noqa: E402
    _secret_ownership_shell_cmd,
    _SECRET_FILES,
    _CONTAINER_UID,
)

# Resolved once, before any test narrows PATH to hide `sudo` — otherwise the
# interpreter itself becomes unfindable and the test fails for the wrong reason.
BASH = shutil.which('bash') or '/bin/bash'


class SecretOwnershipShellTests(unittest.TestCase):

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.bin = os.path.join(self.tmp.name, 'bin')
        os.mkdir(self.bin)
        self.sudo_log = os.path.join(self.tmp.name, 'sudo.log')
        self._write_fake_sudo(rc=0)

    def _write_fake_sudo(self, rc):
        """A `sudo` that records its argv and exits `rc`.

        Hermetic on purpose: a developer with a warm sudo timestamp would
        otherwise have these tests run a real chown against their temp files.
        """
        path = os.path.join(self.bin, 'sudo')
        with open(path, 'w') as fh:
            fh.write(
                "#!/usr/bin/env bash\n"
                f'printf "%s\\n" "$*" >> {shlex.quote(self.sudo_log)}\n'
                f"exit {rc}\n"
            )
        os.chmod(path, 0o755)

    def _secret(self, name, create=True):
        path = os.path.join(self.tmp.name, name)
        if create:
            with open(path, 'w') as fh:
                fh.write('{"API_KEY": "shh"}')
        return path

    def _run(self, files):
        cmd = _secret_ownership_shell_cmd(files=files)
        env = dict(os.environ, PATH=f"{self.bin}:{os.environ['PATH']}")
        return subprocess.run([BASH, '-c', cmd], env=env,
                              capture_output=True, text=True)

    def _sudo_calls(self):
        if not os.path.exists(self.sudo_log):
            return []
        with open(self.sudo_log) as fh:
            return [ln for ln in fh.read().splitlines() if ln.strip()]

    def test_chowns_existing_secret_files_to_the_container_uid(self):
        a = self._secret('org_secrets.json')
        b = self._secret('secret_key')
        result = self._run([a, b])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(self._sudo_calls(), [
            f'-n /bin/chown 33:33 {a}',
            f'-n /bin/chown 33:33 {b}',
        ])

    def test_skips_files_that_do_not_exist(self):
        present = self._secret('org_secrets.json')
        absent = self._secret('secret_key', create=False)
        self._run([present, absent])
        self.assertEqual(self._sudo_calls(), [f'-n /bin/chown 33:33 {present}'])

    def test_no_secret_files_is_a_clean_no_op(self):
        result = self._run([self._secret('org_secrets.json', create=False)])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(self._sudo_calls(), [])

    def test_succeeds_even_when_sudo_is_refused(self):
        """A box whose sudoers predates the chown grant must still complete its
        update; it falls back to the boot-time warning telling the operator
        what to run by hand."""
        self._write_fake_sudo(rc=1)
        result = self._run([self._secret('org_secrets.json')])
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_succeeds_when_sudo_is_missing_entirely(self):
        os.remove(os.path.join(self.bin, 'sudo'))
        secret = self._secret('org_secrets.json')
        cmd = _secret_ownership_shell_cmd(files=[secret])
        # An empty PATH makes `sudo` unresolvable, the harshest version of a
        # box that cannot run it at all.
        result = subprocess.run([BASH, '-c', cmd],
                                env=dict(os.environ, PATH=self.bin),
                                capture_output=True, text=True)
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_uses_sudo_n_so_it_cannot_block_on_a_password(self):
        """`lager update` runs over BatchMode SSH; a sudo that prompts would
        hang the update until its timeout rather than falling through."""
        self.assertIn('sudo -n ', _secret_ownership_shell_cmd())

    def test_does_not_chmod(self):
        """After the chown this user no longer owns the file, so a chmod here
        would fail; the container tightens the mode itself on next load."""
        self.assertNotIn('chmod', _secret_ownership_shell_cmd())

    def test_ships_the_real_paths_and_uid(self):
        cmd = _secret_ownership_shell_cmd()
        self.assertEqual(_CONTAINER_UID, 33)
        self.assertIn('/etc/lager/org_secrets.json', cmd)
        self.assertIn('/etc/lager/secret_key', cmd)
        self.assertIn('33:33', cmd)
        self.assertEqual(
            _SECRET_FILES,
            ('/etc/lager/org_secrets.json', '/etc/lager/secret_key'))

    def test_paths_are_shell_quoted(self):
        cmd = _secret_ownership_shell_cmd(files=['/etc/lager/a b.json'])
        result = subprocess.run([BASH, '-c', cmd], capture_output=True,
                                text=True, env=dict(os.environ, PATH=self.bin))
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("'/etc/lager/a b.json'", cmd)


if __name__ == '__main__':
    unittest.main()
