# Copyright 2024-2026 Lager Data
# SPDX-License-Identifier: Apache-2.0
"""
The admin commands must offer the SSH key Lager itself installs.

`~/.ssh/lager_box` is generated by `lager ssh-setup` / `lager update` and
appended to the box's authorized_keys. It is not one of ssh's default
identity filenames, so a bare `ssh` never tries it: those commands were
relying on the operator's ~/.ssh/config naming an identity for the box, and
on a fleet where that entry is absent (or names a key that has since been
removed) every one of them fails with "Permission denied (publickey)" while
`lager ssh` — which passes -i — keeps working.

The other half is that -i *replaces* ssh's built-in default identity list
rather than adding to it, so offering the key unconditionally would lock out
a box authorized only by a key the operator installed themselves. Every
assertion about "-i is present" here has a counterpart asserting it is not.

No real ssh, no network: subprocess.run is faked throughout.
"""

import importlib
import unittest
from unittest import mock

from click.testing import CliRunner

from cli.commands.box import _ssh
from cli.core import ssh_utils

install_mod = importlib.import_module("cli.commands.utility.install")
uninstall_mod = importlib.import_module("cli.commands.utility.uninstall")
bs = importlib.import_module("cli.box_storage")

KEY = _ssh._LAGER_BOX_KEY
DENIED = "lagerdata@10.0.0.1: Permission denied (publickey).\r\n"


def _proc(rc, stdout="", stderr=""):
    return mock.Mock(returncode=rc, stdout=stdout, stderr=stderr)


def _has_identity(argv):
    """True when argv offers the lager_box key."""
    return "-i" in argv and KEY in argv


class ProbeBoxIdentity(unittest.TestCase):
    """probe_box_identity answers "which identity should this command
    offer?" in at most two connections."""

    def _run(self, *, key_exists=True, results=None, **kwargs):
        calls = []

        def fake_run(cmd, **_kw):
            calls.append(list(cmd))
            return results[len(calls) - 1]

        with mock.patch.object(_ssh.os.path, "exists", return_value=key_exists), \
                mock.patch.object(_ssh.subprocess, "run", fake_run):
            identity, proc = _ssh.probe_box_identity("lagerdata@10.0.0.1", **kwargs)
        return identity, proc, calls

    def test_key_is_offered_and_returned_when_it_works(self):
        identity, _res, calls = self._run(results=[_proc(0, "ok")])
        self.assertEqual(identity, KEY)
        self.assertEqual(len(calls), 1, "one connection when the key works")
        self.assertTrue(_has_identity(calls[0]))

    def test_auth_failure_falls_back_to_default_identities(self):
        identity, proc, calls = self._run(
            results=[_proc(255, "", DENIED), _proc(0, "ok")],
        )
        self.assertIsNone(identity, "the box rejected the key")
        self.assertEqual(proc.returncode, 0, "the fallback attempt is what's returned")
        self.assertEqual(len(calls), 2)
        self.assertTrue(_has_identity(calls[0]))
        self.assertFalse(_has_identity(calls[1]))

    def test_no_key_file_means_no_dash_i_and_no_retry(self):
        # A box that has never had `lager ssh-setup` run against this
        # machine. Nothing to offer, and nothing to fall back to.
        identity, _res, calls = self._run(
            key_exists=False, results=[_proc(255, "", DENIED)],
        )
        self.assertIsNone(identity)
        self.assertEqual(len(calls), 1)
        self.assertFalse(_has_identity(calls[0]))

    def test_transport_failure_is_not_retried(self):
        # "no route to host" fails the same way twice, only slower.
        unreachable = _proc(255, "", "ssh: connect to host 10.0.0.1 port 22: No route to host")
        _identity, proc, calls = self._run(results=[unreachable])
        self.assertEqual(len(calls), 1)
        self.assertIn("No route to host", proc.stderr)

    def test_batch_mode_on_every_attempt(self):
        # BatchMode is what stops a box that authorizes nothing from hanging
        # on a password prompt it would refuse to honor anyway.
        _identity, _res, calls = self._run(
            results=[_proc(255, "", DENIED), _proc(255, "", DENIED)],
        )
        for argv in calls:
            self.assertIn("BatchMode=yes", argv)

    def test_keyed_attempt_isolates_the_key(self):
        """Without IdentitiesOnly, `-i` ADDS the key to a list that still
        holds the agent's keys and any ~/.ssh/config identity for the host,
        so the probe answers "can I reach this box at all?" — it returns the
        key as the working identity on a box where the key is not installed,
        and the keyless fallback can never fire. Observed on hardware: a box
        whose lager_box line had been deleted from authorized_keys probed
        healthy through the operator's own agent key."""
        _identity, _res, calls = self._run(results=[_proc(0, "ok")])
        self.assertIn("IdentitiesOnly=yes", calls[0])

    def test_keyless_attempt_does_not_isolate(self):
        # The fallback's whole job is to let the operator's own identities
        # through; IdentitiesOnly there would offer nothing at all.
        _identity, _res, calls = self._run(
            results=[_proc(255, "", DENIED), _proc(0, "ok")],
        )
        self.assertEqual(len(calls), 2)
        self.assertNotIn("IdentitiesOnly=yes", calls[1])

    def test_extra_args_are_passed_through(self):
        _identity, _res, calls = self._run(
            results=[_proc(0, "ok")],
            extra_args=("-o", "StrictHostKeyChecking=accept-new"),
        )
        self.assertIn("StrictHostKeyChecking=accept-new", calls[0])


class IdentityArgs(unittest.TestCase):
    def test_none_means_ssh_defaults(self):
        self.assertEqual(_ssh.ssh_identity_args(None), [])

    def test_path_becomes_dash_i(self):
        self.assertEqual(_ssh.ssh_identity_args("/k"), ["-i", "/k"])


class KeyRegistration(unittest.TestCase):
    """Installing the key and registering it are different acts.

    ssh-copy-id appends a line to authorized_keys OUTSIDE every manager's
    marker block. start_box.sh preserves such lines against its own rebuild,
    but a second key manager that rebuilds the file from its own source drops
    everything outside its markers — and start_box.sh then re-creates its
    block from /etc/lager/authorized_keys.d alone. A key never registered
    there does not come back, and on a box that also refuses passwords there
    is no way left to put it back. So every install path registers.
    """

    PUB = "ssh-ed25519 AAAATESTBLOB lager-box-access"

    def test_name_is_stable_and_filesystem_safe(self):
        name = _ssh.registered_key_name(user="ci", host="build-01")
        self.assertEqual(name, "lager-box-ci-build-01.pub")
        self.assertEqual(name, _ssh.registered_key_name(user="ci", host="build-01"))

    def test_name_sanitises_hostile_input(self):
        name = _ssh.registered_key_name(user="a/../b", host="x y;rm -rf")
        self.assertRegex(name, r"^lager-box-[A-Za-z0-9._-]+\.pub$")
        for bad in ("/", " ", ";"):
            self.assertNotIn(bad, name)

    def test_one_file_per_machine_so_rerun_replaces_not_accumulates(self):
        # A stale file would leave a superseded key authorized forever.
        self.assertNotIn(self.PUB, _ssh.registered_key_name(user="u", host="h"))
        cmd = _ssh.register_key_command(self.PUB, "lager-box-u-h.pub")
        self.assertIn(">", cmd, "truncating write, not an append")
        self.assertNotIn(">>", cmd)

    def test_command_writes_into_the_key_dir(self):
        cmd = _ssh.register_key_command(self.PUB, "lager-box-u-h.pub")
        self.assertIn(f"{_ssh.BOX_KEYS_DIR}/lager-box-u-h.pub", cmd)
        self.assertIn("mkdir -p", cmd)

    def test_tries_unprivileged_before_sudo(self):
        """On a plain Lager box the key directory belongs to the box and no
        sudo is wanted; the fallback exists for a box whose key manager made
        that directory root-owned, which it did on purpose."""
        cmd = _ssh.register_key_command(self.PUB, "lager-box-u-h.pub")
        plain = cmd.index("> ")
        sudo = cmd.index("sudo -n tee")
        self.assertLess(plain, sudo, "unprivileged write must be attempted first")
        self.assertIn("sudo -n", cmd, "and never sudo without -n: it must not prompt")

    def test_the_documented_grant_cannot_escape_the_key_dir(self):
        """Lager does not install this grant -- it prints it for a fleet that
        scopes sudo tightly to add through its own provisioning. Scoped to
        the filename shape, because a sudoers wildcard does not match '/'."""
        from cli.commands.box.ssh_setup import registration_sudoers_line
        line = registration_sudoers_line("boxuser")
        self.assertIn("NOPASSWD:", line)
        self.assertIn(f"{_ssh.BOX_KEYS_DIR}/lager-box-*.pub", line)
        self.assertTrue(line.startswith("boxuser "))
        # A directory-wide or bare-tee grant would let any file be written.
        self.assertFalse(line.rstrip().endswith("tee"))
        self.assertNotIn(f"tee {_ssh.BOX_KEYS_DIR} ", line)

    def test_failure_is_not_swallowed_by_the_trailing_chmod(self):
        # `A && B && C || true` would return 0 even when the write failed.
        # The `|| true` has to be confined to the chmod alone.
        cmd = _ssh.register_key_command(self.PUB, "lager-box-u-h.pub")
        self.assertTrue(cmd.rstrip().endswith("|| true; }"), cmd)
        self.assertNotIn("&& chmod 644 " + _ssh.BOX_KEYS_DIR, cmd)

    def test_pubkey_is_quoted_into_the_remote_shell(self):
        cmd = _ssh.register_key_command("blob; rm -rf ~", "lager-box-u-h.pub")
        self.assertNotIn("; rm -rf ~ ", cmd)
        self.assertIn("'blob; rm -rf ~'", cmd)

    def _register(self, *, rc=0, stderr="", pub=PUB):
        calls = []

        def fake_run(cmd, **_kw):
            calls.append(list(cmd))
            return _proc(rc, "", stderr)

        with mock.patch("builtins.open", mock.mock_open(read_data=pub)), \
                mock.patch.object(_ssh.subprocess, "run", fake_run):
            ok, detail = _ssh.register_lager_box_key("lagerdata@10.0.0.1")
        return ok, detail, calls

    def test_registers_over_the_key_so_it_costs_no_password(self):
        ok, _detail, calls = self._register()
        self.assertTrue(ok)
        self.assertTrue(_has_identity(calls[0]))
        self.assertIn("BatchMode=yes", calls[0])

    def test_failure_is_reported_not_raised(self):
        # The key is already installed and working by this point; a
        # read-only /etc/lager must not fail the whole command.
        ok, detail, _calls = self._register(rc=1, stderr="Permission denied")
        self.assertFalse(ok)
        self.assertIn("Permission denied", detail)

    def test_empty_pubkey_never_reaches_the_box(self):
        ok, detail, calls = self._register(pub="   \n")
        self.assertFalse(ok)
        self.assertIn("empty", detail)
        self.assertEqual(calls, [], "nothing sent")


class KeyInstalledOnBox(unittest.TestCase):
    """"Is the key on the box?" cannot be answered by logging in.

    A login proves only that SOME identity worked, and an operator whose
    ssh_config carries a `Host *` IdentityFile — a common fleet-management
    layout — has one for every host. Measured on hardware: a box that
    answered the auth probe rejected lager_box outright under
    `ssh -F /dev/null`, and because ssh-setup and update both gated their
    reinstall on that probe, neither could ever repair it.
    """

    PUB = "ssh-ed25519 AAAATESTBLOB lager-box-access"

    def _check(self, rc, *, pub=PUB):
        calls = []

        def fake_run(cmd, **_kw):
            calls.append(list(cmd))
            return _proc(rc)

        with mock.patch("builtins.open", mock.mock_open(read_data=pub)), \
                mock.patch.object(_ssh.shutil, "which", lambda _n: "/usr/bin/ssh"), \
                mock.patch.object(_ssh.subprocess, "run", fake_run):
            return _ssh.key_installed_on_box("lagerdata@10.0.0.1"), calls

    def test_greps_authorized_keys_for_the_blob_not_the_comment(self):
        # Comments drift -- the same key is `lager-box-access` locally and
        # whatever a key manager rendered it as on the box. The blob is the key.
        result, calls = self._check(0)
        self.assertIs(result, True)
        remote = calls[0][-1]
        self.assertIn("AAAATESTBLOB", remote)
        self.assertIn("authorized_keys", remote)
        self.assertNotIn("lager-box-access", remote)

    def test_grep_no_match_means_not_installed(self):
        self.assertIs(self._check(1)[0], False)

    def test_missing_authorized_keys_means_not_installed(self):
        # grep exits 2 for a missing file.
        self.assertIs(self._check(2)[0], False)

    def test_unreachable_box_is_unknown_not_absent(self):
        # 255 is ssh failing to get there; treating that as "not installed"
        # would trigger a pointless reinstall, and as "installed" would skip
        # a needed one. Neither is honest.
        self.assertIsNone(self._check(255)[0])

    def test_no_local_pubkey_is_unknown_and_asks_nothing(self):
        result, calls = self._check(0, pub="")
        self.assertIsNone(result)
        self.assertEqual(calls, [])

    def test_does_not_force_the_key_for_the_query_itself(self):
        # This is a question about the box's state, not about which
        # credential asks it -- any working identity is fine.
        _result, calls = self._check(0)
        self.assertNotIn("IdentitiesOnly=yes", calls[0])
        self.assertIn("BatchMode=yes", calls[0])


class DeployScriptKeyCheck(unittest.TestCase):
    """The deploy script asks the same question the CLI does, the same way.

    It used to decide "is SSH set up?" by connecting, and fell through to a
    bare `ssh <box> echo test` when the keyed attempt failed. On a machine
    with an ssh_config `Host *` IdentityFile that bare probe always
    succeeds, so the script reported "Passwordless SSH already configured"
    and skipped generating, copying, and registering the key — on hardware,
    an install that reported success and left the box without a lager_box
    key at all.
    """

    @classmethod
    def setUpClass(cls):
        from pathlib import Path
        import cli
        cls.script = (Path(cli.__file__).parent / "deployment" / "scripts"
                      / "setup_and_deploy_box.sh").read_text()

    def _probe_block(self):
        start = self.script.index('print_info "Testing existing SSH configuration')
        return self.script[start:self.script.index("\nfi", start)]

    def test_it_greps_authorized_keys_rather_than_connecting(self):
        block = self._probe_block()
        self.assertIn("grep -qF", block)
        self.assertIn("authorized_keys", block)

    def test_no_bare_reachability_fallback(self):
        # `elif ssh ... "echo 'test'"` is the exact shape that made an
        # install skip key setup on a box that had no lager_box key.
        block = self._probe_block()
        self.assertNotIn("elif ssh", block)
        self.assertNotIn("echo 'test'", block)

    def test_missing_local_pubkey_means_set_it_up(self):
        # A first install has no key yet; the guard must not read an empty
        # blob as "already authorized".
        block = self._probe_block()
        self.assertIn('[ -n "$KEY_BLOB" ]', block)
        self.assertIn("NEEDS_SSH_SETUP=true", block)


class ConnectionPoolIdentity(unittest.TestCase):
    """The pool has to carry the identity too. ControlMaster=auto silently
    opens a fresh connection when the socket is gone, and that one
    authenticates for real."""

    def _pool(self):
        pool = ssh_utils.SSHConnectionPool.__new__(ssh_utils.SSHConnectionPool)
        pool.control_dir = ssh_utils.Path("/tmp/lager-test-control")
        pool._identities = {}
        return pool

    def _ensure(self, pool, results, **kwargs):
        """Drive ensure_connection with `results` for [check, start, start...].

        The master start hands ssh a real file for stderr rather than a pipe,
        so the fake writes there like ssh would.
        """
        calls = []
        kwargs_seen = []

        def fake_run(cmd, **kw):
            calls.append(list(cmd))
            kwargs_seen.append(kw)
            result = results[len(calls) - 1]
            errf = kw.get("stderr")
            if hasattr(errf, "write") and result.stderr:
                errf.write(result.stderr)
            return result

        with mock.patch.object(ssh_utils.subprocess, "run", fake_run), \
                mock.patch.object(ssh_utils.time, "sleep", lambda _s: None):
            ok = pool.ensure_connection("10.0.0.1", "lagerdata", **kwargs)
        self._kwargs_seen = kwargs_seen
        return ok, calls

    def test_master_offers_the_key_and_options_re_offer_it(self):
        pool = self._pool()
        with mock.patch.object(ssh_utils, "_auto_identity_candidates", return_value=[KEY, None]):
            ok, calls = self._ensure(pool, [_proc(1), _proc(0)])
        self.assertTrue(ok)
        self.assertTrue(_has_identity(calls[1]), "master start offers the key")
        self.assertTrue(_has_identity(pool.get_ssh_options("10.0.0.1")))

    def test_master_retries_without_the_key_when_rejected(self):
        pool = self._pool()
        with mock.patch.object(ssh_utils, "_auto_identity_candidates", return_value=[KEY, None]):
            ok, calls = self._ensure(pool, [_proc(1), _proc(255, "", DENIED), _proc(0)])
        self.assertTrue(ok)
        self.assertEqual(len(calls), 3)
        self.assertFalse(_has_identity(calls[2]))
        self.assertIsNone(pool.identity_for("10.0.0.1"))
        self.assertNotIn("-i", pool.get_ssh_options("10.0.0.1"))

    def test_master_does_not_retry_a_transport_failure(self):
        pool = self._pool()
        unreachable = _proc(255, "", "ssh: connect to host 10.0.0.1 port 22: Connection timed out")
        with mock.patch.object(ssh_utils, "_auto_identity_candidates", return_value=[KEY, None]):
            ok, calls = self._ensure(pool, [_proc(1), unreachable])
        self.assertFalse(ok)
        self.assertEqual(len(calls), 2, "check + one doomed master start")

    def test_explicit_identity_is_honored_over_auto_detection(self):
        # A caller that already probed passes its answer; None means "this
        # box does not take the key", and must not be re-derived.
        pool = self._pool()
        with mock.patch.object(ssh_utils, "_auto_identity_candidates", return_value=[KEY, None]):
            ok, calls = self._ensure(pool, [_proc(1), _proc(0)], identity_file=None)
        self.assertTrue(ok)
        self.assertFalse(_has_identity(calls[1]))

    def test_no_identity_learned_means_no_dash_i_in_options(self):
        pool = self._pool()
        self.assertNotIn("-i", pool.get_ssh_options("10.0.0.1"))

    def test_master_stderr_is_a_file_not_a_pipe(self):
        """`ssh -fNM` daemonizes without closing its inherited descriptors,
        so it holds the write end of a pipe open for its whole
        ControlPersist life. Reading that pipe blocks until the timeout —
        every successful master start would become a 15s hang and a False
        return, silently disabling multiplexing everywhere."""
        pool = self._pool()
        with mock.patch.object(ssh_utils, "_auto_identity_candidates", return_value=[None]):
            ok, calls = self._ensure(pool, [_proc(1), _proc(0)])
        self.assertTrue(ok)
        start_kwargs = self._kwargs_seen[1]
        self.assertNotIn("capture_output", start_kwargs)
        self.assertNotEqual(start_kwargs.get("stderr"), ssh_utils.subprocess.PIPE)
        self.assertTrue(hasattr(start_kwargs.get("stderr"), "write"),
                        "stderr must be a real file object")


class _CommandCase(unittest.TestCase):
    """Drives install/uninstall over a faked SSH transport.

    ``subprocess.run`` is patched on the module object itself, so the probe
    in cli.commands.box._ssh sees the fake too.
    """

    def _lock_patches(self):
        return [
            mock.patch.object(bs, "acquire_box_lock", return_value=("acquired", {})),
            mock.patch.object(bs, "release_box_lock", return_value=True),
            mock.patch.object(bs, "get_lock_holder", return_value="test-holder"),
            mock.patch.object(bs, "HeartbeatThread", return_value=mock.Mock()),
        ]

    def _ssh_calls(self, calls):
        return [argv for argv in calls if argv and argv[0] == "ssh"]


class InstallOffersTheKey(_CommandCase):
    def _install(self, *, key_exists=True, key_accepted=True):
        calls = []

        def fake_run(cmd, **_kw):
            cmd = list(cmd) if isinstance(cmd, (list, tuple)) else [cmd]
            calls.append(cmd)
            if cmd and cmd[0] != "ssh":
                return _proc(0)  # the deploy script
            if _has_identity(cmd) and not key_accepted:
                return _proc(255, "", DENIED)
            # Report the sudoers grant as not yet installed, so the
            # interactive `ssh -t` bootstrap runs and is covered too.
            if install_mod.BOXCFG_SUDOERS_MARKER in cmd[-1]:
                return _proc(1)
            return _proc(0, "0.36.2\n")

        patches = self._lock_patches() + [
            mock.patch.object(install_mod.subprocess, "run", fake_run),
            mock.patch.object(_ssh.os.path, "exists", return_value=key_exists),
        ]
        for p in patches:
            p.start()
            self.addCleanup(p.stop)
        result = CliRunner().invoke(install_mod.install, ["--ip", "10.0.0.1", "--yes"])
        return result, self._ssh_calls(calls)

    def test_every_ssh_call_offers_the_key(self):
        result, calls = self._install()
        self.assertEqual(result.exit_code, 0, result.output)
        self.assertGreater(len(calls), 1, "sanity: install talked to the box")
        for argv in calls:
            self.assertTrue(_has_identity(argv), argv)

    def test_no_key_file_leaves_every_call_bare(self):
        # A fresh box reachable only by the operator's own key: -i would
        # suppress the very identities that work.
        result, calls = self._install(key_exists=False)
        self.assertEqual(result.exit_code, 0, result.output)
        self.assertTrue(calls, "sanity: install talked to the box")
        for argv in calls:
            self.assertNotIn("-i", argv, argv)


class InstallHasNoPasswordFallback(_CommandCase):
    """A hardened box sets PasswordAuthentication no, so ssh never sent the
    password install had just asked for — and then reported a password
    failure for what was an identity failure."""

    def _install_rejected(self, *, decline=False, provision=None):
        """Drive install against a box that authorizes nothing.

        `provision` replaces the key-setup helper; None means "the box
        refuses the key too", which is what a box with
        PasswordAuthentication no does.
        """
        calls = []

        def fake_run(cmd, **_kw):
            cmd = list(cmd) if isinstance(cmd, (list, tuple)) else [cmd]
            calls.append(cmd)
            # The deploy script; only SSH is being refused here.
            if cmd and cmd[0] != "ssh":
                return _proc(0)
            return _proc(255, "", DENIED)

        def refuses(dest, **_kw):
            raise install_mod.LagerError(f"ssh-copy-id to {dest} failed.")

        patches = self._lock_patches() + [
            mock.patch.object(install_mod.subprocess, "run", fake_run),
            mock.patch.object(_ssh.os.path, "exists", return_value=True),
            mock.patch.object(install_mod, "provision_lager_box_key",
                              provision or refuses),
        ]
        for p in patches:
            p.start()
            self.addCleanup(p.stop)
        args = ["--ip", "10.0.0.1"] + ([] if decline else ["--yes"])
        result = CliRunner().invoke(install_mod.install, args, input="n\n")
        return result, self._ssh_calls(calls)

    def test_it_sets_the_key_up_rather_than_dead_ending(self):
        # Install used to stop and tell you to run `lager ssh-setup` first.
        # The password it would have asked for is the same one install needs,
        # so it does that work itself now.
        provisioned = []
        result, _calls = self._install_rejected(
            provision=lambda dest, **_kw: provisioned.append(dest) or False)
        self.assertEqual(provisioned, ["lagerdata@10.0.0.1"])
        self.assertEqual(result.exit_code, 0, result.output)

    def test_declining_still_names_the_command_that_fixes_it(self):
        result, _calls = self._install_rejected(decline=True)
        self.assertNotEqual(result.exit_code, 0)
        self.assertIn("lager ssh-setup", result.output)

    def test_a_setup_failure_keeps_its_own_guidance(self):
        # The provisioning error is raised inside install's broad
        # `except Exception`, which would re-wrap it as a generic
        # "SSH connectivity check failed" and discard what it said.
        result, _calls = self._install_rejected()
        self.assertNotEqual(result.exit_code, 0)
        self.assertIn("ssh-copy-id", result.output)
        self.assertNotIn("SSH connectivity check failed", result.output)

    def test_no_password_prompt_is_ever_attempted(self):
        _result, calls = self._install_rejected()
        for argv in calls:
            self.assertNotIn("NumberOfPasswordPrompts=1", argv, argv)

    def test_it_probed_with_the_key_before_giving_up(self):
        # Offering to install the key is only honest if it really was tried.
        _result, calls = self._install_rejected()
        self.assertTrue(any(_has_identity(argv) for argv in calls))
        self.assertTrue(any(not _has_identity(argv) for argv in calls),
                        "and the default identities were tried too")


class UninstallOffersTheKey(_CommandCase):
    def _uninstall(self, *, key_exists=True, key_accepted=True):
        calls = []

        def fake_run(cmd, **_kw):
            cmd = list(cmd) if isinstance(cmd, (list, tuple)) else [cmd]
            calls.append(cmd)
            remote = cmd[-1]
            if _has_identity(cmd) and not key_accepted:
                return _proc(255, "", DENIED)
            if remote.startswith("cat ") and uninstall_mod._PRIV_RESULTS_PATH in remote:
                return _proc(0, "lock_state=OK\n")
            return _proc(0, "ok")

        # Force the un-multiplexed path so the command's own identity
        # threading — not the pool's — is what is under test.
        pool = mock.Mock()
        pool.ensure_connection.return_value = False

        patches = self._lock_patches() + [
            mock.patch.object(uninstall_mod.subprocess, "run", fake_run),
            mock.patch.object(uninstall_mod, "get_ssh_connection_pool", return_value=pool),
            mock.patch.object(uninstall_mod, "get_box_name_by_ip", return_value=None),
            mock.patch.object(_ssh.os.path, "exists", return_value=key_exists),
        ]
        for p in patches:
            p.start()
            self.addCleanup(p.stop)
        result = CliRunner().invoke(
            uninstall_mod.uninstall, ["--ip", "10.0.0.1", "--yes", "--keep-config"],
        )
        return result, self._ssh_calls(calls), pool

    def test_every_teardown_command_offers_the_key(self):
        result, calls, _pool = self._uninstall()
        self.assertEqual(result.exit_code, 0, result.output)
        self.assertGreater(len(calls), 5, "sanity: the teardown ran")
        for argv in calls:
            self.assertTrue(_has_identity(argv), argv)

    def test_the_probe_result_is_handed_to_the_pool(self):
        _result, _calls, pool = self._uninstall()
        self.assertEqual(
            pool.ensure_connection.call_args.kwargs.get("identity_file"), KEY,
        )

    def test_a_box_that_rejects_the_key_keeps_working(self):
        result, calls, _pool = self._uninstall(key_accepted=False)
        self.assertEqual(result.exit_code, 0, result.output)
        teardown = [a for a in calls if a[-1] != "echo ok"]
        self.assertTrue(teardown, "sanity: the teardown ran")
        for argv in teardown:
            self.assertNotIn("-i", argv, argv)

    def test_no_key_file_leaves_every_call_bare(self):
        result, calls, _pool = self._uninstall(key_exists=False)
        self.assertEqual(result.exit_code, 0, result.output)
        for argv in calls:
            self.assertNotIn("-i", argv, argv)


class UninstallDeregisters(_CommandCase):
    """--all strips the authorized_keys line. Without also removing the
    registration, --keep-config preserves /etc/lager and the next
    start_box.sh sync republishes the key uninstall just removed."""

    def test_all_removes_the_registered_pubkey_first(self):
        calls = []

        def fake_run(cmd, **_kw):
            cmd = list(cmd) if isinstance(cmd, (list, tuple)) else [cmd]
            calls.append(cmd)
            remote = cmd[-1]
            if remote.startswith("cat ") and uninstall_mod._PRIV_RESULTS_PATH in remote:
                return _proc(0, "lock_state=OK\n")
            return _proc(0, "ok")

        pool = mock.Mock()
        pool.ensure_connection.return_value = False
        patches = self._lock_patches() + [
            mock.patch.object(uninstall_mod.subprocess, "run", fake_run),
            mock.patch.object(uninstall_mod, "get_ssh_connection_pool", return_value=pool),
            mock.patch.object(uninstall_mod, "get_box_name_by_ip", return_value=None),
            mock.patch.object(_ssh.os.path, "exists", return_value=True),
        ]
        for p in patches:
            p.start()
            self.addCleanup(p.stop)
        result = CliRunner().invoke(
            uninstall_mod.uninstall,
            ["--ip", "10.0.0.1", "--yes", "--keep-config", "--all"],
        )
        self.assertEqual(result.exit_code, 0, result.output)

        remotes = [c[-1] for c in self._ssh_calls(calls)]
        dereg = [i for i, r in enumerate(remotes)
                 if uninstall_mod.BOX_KEYS_DIR in r and r.startswith("rm -f")]
        strip = [i for i, r in enumerate(remotes) if "authorized_keys" in r and "grep -vF" in r]
        self.assertTrue(dereg, f"no de-registration in {remotes}")
        self.assertTrue(strip, "sanity: the authorized_keys strip still runs")
        self.assertLess(dereg[0], strip[0], "de-register before stripping")

    def test_it_names_only_this_machines_file(self):
        # A glob would revoke every other operator's registration.
        cmd = f"rm -f {uninstall_mod.BOX_KEYS_DIR}/{uninstall_mod.registered_key_name()}"
        self.assertNotIn("*", cmd)

if __name__ == "__main__":
    unittest.main()
