# Copyright 2024-2026 Lager Data
# SPDX-License-Identifier: Apache-2.0
"""
The admin commands must offer the SSH key Lager itself installs.

`~/.ssh/lager_box` is generated by `lager ssh-setup` / `lager update` and
appended to the box's authorized_keys. It is not one of ssh's default
identity filenames, so a bare `ssh` never tries it: those commands were
relying on the operator's ~/.ssh/config naming an identity for the box, and
on a fleet where that entry is absent (or names a key that has since been
removed) every one of them fails with "Permission denied (publickey)" while
`lager ssh` — which passes -i — keeps working.

The other half is that -i *replaces* ssh's built-in default identity list
rather than adding to it, so offering the key unconditionally would lock out
a box authorized only by a key the operator installed themselves. Every
assertion about "-i is present" here has a counterpart asserting it is not.

No real ssh, no network: subprocess.run is faked throughout.
"""

import importlib
import unittest
from unittest import mock

from click.testing import CliRunner

from cli.commands.box import _ssh
from cli.core import ssh_utils

install_mod = importlib.import_module("cli.commands.utility.install")
uninstall_mod = importlib.import_module("cli.commands.utility.uninstall")
bs = importlib.import_module("cli.box_storage")

KEY = _ssh._LAGER_BOX_KEY
DENIED = "lagerdata@10.0.0.1: Permission denied (publickey).\r\n"


def _proc(rc, stdout="", stderr=""):
    return mock.Mock(returncode=rc, stdout=stdout, stderr=stderr)


def _has_identity(argv):
    """True when argv offers the lager_box key."""
    return "-i" in argv and KEY in argv


class ProbeBoxIdentity(unittest.TestCase):
    """probe_box_identity answers "which identity should this command
    offer?" in at most two connections."""

    def _run(self, *, key_exists=True, results=None, **kwargs):
        calls = []

        def fake_run(cmd, **_kw):
            calls.append(list(cmd))
            return results[len(calls) - 1]

        with mock.patch.object(_ssh.os.path, "exists", return_value=key_exists), \
                mock.patch.object(_ssh.subprocess, "run", fake_run):
            identity, proc = _ssh.probe_box_identity("lagerdata@10.0.0.1", **kwargs)
        return identity, proc, calls

    def test_key_is_offered_and_returned_when_it_works(self):
        identity, _res, calls = self._run(results=[_proc(0, "ok")])
        self.assertEqual(identity, KEY)
        self.assertEqual(len(calls), 1, "one connection when the key works")
        self.assertTrue(_has_identity(calls[0]))

    def test_auth_failure_falls_back_to_default_identities(self):
        identity, proc, calls = self._run(
            results=[_proc(255, "", DENIED), _proc(0, "ok")],
        )
        self.assertIsNone(identity, "the box rejected the key")
        self.assertEqual(proc.returncode, 0, "the fallback attempt is what's returned")
        self.assertEqual(len(calls), 2)
        self.assertTrue(_has_identity(calls[0]))
        self.assertFalse(_has_identity(calls[1]))

    def test_no_key_file_means_no_dash_i_and_no_retry(self):
        # A box that has never had `lager ssh-setup` run against this
        # machine. Nothing to offer, and nothing to fall back to.
        identity, _res, calls = self._run(
            key_exists=False, results=[_proc(255, "", DENIED)],
        )
        self.assertIsNone(identity)
        self.assertEqual(len(calls), 1)
        self.assertFalse(_has_identity(calls[0]))

    def test_transport_failure_is_not_retried(self):
        # "no route to host" fails the same way twice, only slower.
        unreachable = _proc(255, "", "ssh: connect to host 10.0.0.1 port 22: No route to host")
        _identity, proc, calls = self._run(results=[unreachable])
        self.assertEqual(len(calls), 1)
        self.assertIn("No route to host", proc.stderr)

    def test_batch_mode_on_every_attempt(self):
        # BatchMode is what stops a box that authorizes nothing from hanging
        # on a password prompt it would refuse to honor anyway.
        _identity, _res, calls = self._run(
            results=[_proc(255, "", DENIED), _proc(255, "", DENIED)],
        )
        for argv in calls:
            self.assertIn("BatchMode=yes", argv)

    def test_extra_args_are_passed_through(self):
        _identity, _res, calls = self._run(
            results=[_proc(0, "ok")],
            extra_args=("-o", "StrictHostKeyChecking=accept-new"),
        )
        self.assertIn("StrictHostKeyChecking=accept-new", calls[0])


class IdentityArgs(unittest.TestCase):
    def test_none_means_ssh_defaults(self):
        self.assertEqual(_ssh.ssh_identity_args(None), [])

    def test_path_becomes_dash_i(self):
        self.assertEqual(_ssh.ssh_identity_args("/k"), ["-i", "/k"])


class ConnectionPoolIdentity(unittest.TestCase):
    """The pool has to carry the identity too. ControlMaster=auto silently
    opens a fresh connection when the socket is gone, and that one
    authenticates for real."""

    def _pool(self):
        pool = ssh_utils.SSHConnectionPool.__new__(ssh_utils.SSHConnectionPool)
        pool.control_dir = ssh_utils.Path("/tmp/lager-test-control")
        pool._identities = {}
        return pool

    def _ensure(self, pool, results, **kwargs):
        """Drive ensure_connection with `results` for [check, start, start...].

        The master start hands ssh a real file for stderr rather than a pipe,
        so the fake writes there like ssh would.
        """
        calls = []
        kwargs_seen = []

        def fake_run(cmd, **kw):
            calls.append(list(cmd))
            kwargs_seen.append(kw)
            result = results[len(calls) - 1]
            errf = kw.get("stderr")
            if hasattr(errf, "write") and result.stderr:
                errf.write(result.stderr)
            return result

        with mock.patch.object(ssh_utils.subprocess, "run", fake_run), \
                mock.patch.object(ssh_utils.time, "sleep", lambda _s: None):
            ok = pool.ensure_connection("10.0.0.1", "lagerdata", **kwargs)
        self._kwargs_seen = kwargs_seen
        return ok, calls

    def test_master_offers_the_key_and_options_re_offer_it(self):
        pool = self._pool()
        with mock.patch.object(ssh_utils, "_auto_identity_candidates", return_value=[KEY, None]):
            ok, calls = self._ensure(pool, [_proc(1), _proc(0)])
        self.assertTrue(ok)
        self.assertTrue(_has_identity(calls[1]), "master start offers the key")
        self.assertTrue(_has_identity(pool.get_ssh_options("10.0.0.1")))

    def test_master_retries_without_the_key_when_rejected(self):
        pool = self._pool()
        with mock.patch.object(ssh_utils, "_auto_identity_candidates", return_value=[KEY, None]):
            ok, calls = self._ensure(pool, [_proc(1), _proc(255, "", DENIED), _proc(0)])
        self.assertTrue(ok)
        self.assertEqual(len(calls), 3)
        self.assertFalse(_has_identity(calls[2]))
        self.assertIsNone(pool.identity_for("10.0.0.1"))
        self.assertNotIn("-i", pool.get_ssh_options("10.0.0.1"))

    def test_master_does_not_retry_a_transport_failure(self):
        pool = self._pool()
        unreachable = _proc(255, "", "ssh: connect to host 10.0.0.1 port 22: Connection timed out")
        with mock.patch.object(ssh_utils, "_auto_identity_candidates", return_value=[KEY, None]):
            ok, calls = self._ensure(pool, [_proc(1), unreachable])
        self.assertFalse(ok)
        self.assertEqual(len(calls), 2, "check + one doomed master start")

    def test_explicit_identity_is_honored_over_auto_detection(self):
        # A caller that already probed passes its answer; None means "this
        # box does not take the key", and must not be re-derived.
        pool = self._pool()
        with mock.patch.object(ssh_utils, "_auto_identity_candidates", return_value=[KEY, None]):
            ok, calls = self._ensure(pool, [_proc(1), _proc(0)], identity_file=None)
        self.assertTrue(ok)
        self.assertFalse(_has_identity(calls[1]))

    def test_no_identity_learned_means_no_dash_i_in_options(self):
        pool = self._pool()
        self.assertNotIn("-i", pool.get_ssh_options("10.0.0.1"))

    def test_master_stderr_is_a_file_not_a_pipe(self):
        """`ssh -fNM` daemonizes without closing its inherited descriptors,
        so it holds the write end of a pipe open for its whole
        ControlPersist life. Reading that pipe blocks until the timeout —
        every successful master start would become a 15s hang and a False
        return, silently disabling multiplexing everywhere."""
        pool = self._pool()
        with mock.patch.object(ssh_utils, "_auto_identity_candidates", return_value=[None]):
            ok, calls = self._ensure(pool, [_proc(1), _proc(0)])
        self.assertTrue(ok)
        start_kwargs = self._kwargs_seen[1]
        self.assertNotIn("capture_output", start_kwargs)
        self.assertNotEqual(start_kwargs.get("stderr"), ssh_utils.subprocess.PIPE)
        self.assertTrue(hasattr(start_kwargs.get("stderr"), "write"),
                        "stderr must be a real file object")


class _CommandCase(unittest.TestCase):
    """Drives install/uninstall over a faked SSH transport.

    ``subprocess.run`` is patched on the module object itself, so the probe
    in cli.commands.box._ssh sees the fake too.
    """

    def _lock_patches(self):
        return [
            mock.patch.object(bs, "acquire_box_lock", return_value=("acquired", {})),
            mock.patch.object(bs, "release_box_lock", return_value=True),
            mock.patch.object(bs, "get_lock_holder", return_value="test-holder"),
            mock.patch.object(bs, "HeartbeatThread", return_value=mock.Mock()),
        ]

    def _ssh_calls(self, calls):
        return [argv for argv in calls if argv and argv[0] == "ssh"]


class InstallOffersTheKey(_CommandCase):
    def _install(self, *, key_exists=True, key_accepted=True):
        calls = []

        def fake_run(cmd, **_kw):
            cmd = list(cmd) if isinstance(cmd, (list, tuple)) else [cmd]
            calls.append(cmd)
            if cmd and cmd[0] != "ssh":
                return _proc(0)  # the deploy script
            if _has_identity(cmd) and not key_accepted:
                return _proc(255, "", DENIED)
            # Report the sudoers grant as not yet installed, so the
            # interactive `ssh -t` bootstrap runs and is covered too.
            if install_mod.BOXCFG_SUDOERS_MARKER in cmd[-1]:
                return _proc(1)
            return _proc(0, "0.36.2\n")

        patches = self._lock_patches() + [
            mock.patch.object(install_mod.subprocess, "run", fake_run),
            mock.patch.object(_ssh.os.path, "exists", return_value=key_exists),
        ]
        for p in patches:
            p.start()
            self.addCleanup(p.stop)
        result = CliRunner().invoke(install_mod.install, ["--ip", "10.0.0.1", "--yes"])
        return result, self._ssh_calls(calls)

    def test_every_ssh_call_offers_the_key(self):
        result, calls = self._install()
        self.assertEqual(result.exit_code, 0, result.output)
        self.assertGreater(len(calls), 1, "sanity: install talked to the box")
        for argv in calls:
            self.assertTrue(_has_identity(argv), argv)

    def test_no_key_file_leaves_every_call_bare(self):
        # A fresh box reachable only by the operator's own key: -i would
        # suppress the very identities that work.
        result, calls = self._install(key_exists=False)
        self.assertEqual(result.exit_code, 0, result.output)
        self.assertTrue(calls, "sanity: install talked to the box")
        for argv in calls:
            self.assertNotIn("-i", argv, argv)


class InstallHasNoPasswordFallback(_CommandCase):
    """A hardened box sets PasswordAuthentication no, so ssh never sent the
    password install had just asked for — and then reported a password
    failure for what was an identity failure."""

    def _install_rejected(self):
        calls = []

        def fake_run(cmd, **_kw):
            cmd = list(cmd) if isinstance(cmd, (list, tuple)) else [cmd]
            calls.append(cmd)
            return _proc(255, "", DENIED)

        patches = self._lock_patches() + [
            mock.patch.object(install_mod.subprocess, "run", fake_run),
            mock.patch.object(_ssh.os.path, "exists", return_value=True),
        ]
        for p in patches:
            p.start()
            self.addCleanup(p.stop)
        result = CliRunner().invoke(install_mod.install, ["--ip", "10.0.0.1", "--yes"])
        return result, self._ssh_calls(calls)

    def test_it_fails_instead_of_prompting(self):
        result, _calls = self._install_rejected()
        self.assertNotEqual(result.exit_code, 0)
        self.assertNotIn("password authentication", result.output.lower())

    def test_the_error_names_the_command_that_fixes_it(self):
        result, _calls = self._install_rejected()
        self.assertIn("lager ssh-setup", result.output)

    def test_no_password_prompt_is_ever_attempted(self):
        _result, calls = self._install_rejected()
        for argv in calls:
            self.assertNotIn("NumberOfPasswordPrompts=1", argv, argv)

    def test_it_probed_with_the_key_before_giving_up(self):
        # The error is only honest if the key really was offered.
        _result, calls = self._install_rejected()
        self.assertTrue(any(_has_identity(argv) for argv in calls))
        self.assertTrue(any(not _has_identity(argv) for argv in calls),
                        "and the default identities were tried too")


class UninstallOffersTheKey(_CommandCase):
    def _uninstall(self, *, key_exists=True, key_accepted=True):
        calls = []

        def fake_run(cmd, **_kw):
            cmd = list(cmd) if isinstance(cmd, (list, tuple)) else [cmd]
            calls.append(cmd)
            remote = cmd[-1]
            if _has_identity(cmd) and not key_accepted:
                return _proc(255, "", DENIED)
            if remote.startswith("cat ") and uninstall_mod._PRIV_RESULTS_PATH in remote:
                return _proc(0, "lock_state=OK\n")
            return _proc(0, "ok")

        # Force the un-multiplexed path so the command's own identity
        # threading — not the pool's — is what is under test.
        pool = mock.Mock()
        pool.ensure_connection.return_value = False

        patches = self._lock_patches() + [
            mock.patch.object(uninstall_mod.subprocess, "run", fake_run),
            mock.patch.object(uninstall_mod, "get_ssh_connection_pool", return_value=pool),
            mock.patch.object(uninstall_mod, "get_box_name_by_ip", return_value=None),
            mock.patch.object(_ssh.os.path, "exists", return_value=key_exists),
        ]
        for p in patches:
            p.start()
            self.addCleanup(p.stop)
        result = CliRunner().invoke(
            uninstall_mod.uninstall, ["--ip", "10.0.0.1", "--yes", "--keep-config"],
        )
        return result, self._ssh_calls(calls), pool

    def test_every_teardown_command_offers_the_key(self):
        result, calls, _pool = self._uninstall()
        self.assertEqual(result.exit_code, 0, result.output)
        self.assertGreater(len(calls), 5, "sanity: the teardown ran")
        for argv in calls:
            self.assertTrue(_has_identity(argv), argv)

    def test_the_probe_result_is_handed_to_the_pool(self):
        _result, _calls, pool = self._uninstall()
        self.assertEqual(
            pool.ensure_connection.call_args.kwargs.get("identity_file"), KEY,
        )

    def test_a_box_that_rejects_the_key_keeps_working(self):
        result, calls, _pool = self._uninstall(key_accepted=False)
        self.assertEqual(result.exit_code, 0, result.output)
        teardown = [a for a in calls if a[-1] != "echo ok"]
        self.assertTrue(teardown, "sanity: the teardown ran")
        for argv in teardown:
            self.assertNotIn("-i", argv, argv)

    def test_no_key_file_leaves_every_call_bare(self):
        result, calls, _pool = self._uninstall(key_exists=False)
        self.assertEqual(result.exit_code, 0, result.output)
        for argv in calls:
            self.assertNotIn("-i", argv, argv)


if __name__ == "__main__":
    unittest.main()
