# Copyright 2024-2026 Lager Data
# SPDX-License-Identifier: Apache-2.0
"""
The admin commands must offer the SSH key Lager itself installs.

`~/.ssh/lager_box` is generated by `lager ssh-setup` / `lager update` and
appended to the box's authorized_keys. It is not one of ssh's default
identity filenames, so a bare `ssh` never tries it: those commands were
relying on the operator's ~/.ssh/config naming an identity for the box, and
on a fleet where that entry is absent (or names a key that has since been
removed) every one of them fails with "Permission denied (publickey)" while
`lager ssh` — which passes -i — keeps working.

The other half is that -i *replaces* ssh's built-in default identity list
rather than adding to it, so offering the key unconditionally would lock out
a box authorized only by a key the operator installed themselves. Every
assertion about "-i is present" here has a counterpart asserting it is not.

No real ssh, no network: subprocess.run is faked throughout.
"""

import importlib
import os
import pathlib
import subprocess
import tempfile
import unittest
from unittest import mock

from click.testing import CliRunner

from cli.commands.box import _ssh
from cli.core import ssh_utils

install_mod = importlib.import_module("cli.commands.utility.install")
uninstall_mod = importlib.import_module("cli.commands.utility.uninstall")
ssh_mod = importlib.import_module("cli.commands.box.ssh")
bs = importlib.import_module("cli.box_storage")

KEY = _ssh._LAGER_BOX_KEY
DENIED = "lagerdata@10.0.0.1: Permission denied (publickey).\r\n"


def _proc(rc, stdout="", stderr=""):
    return mock.Mock(returncode=rc, stdout=stdout, stderr=stderr)


def _fake_key_if_present(key_exists):
    """Stand-in for lager_box_key_if_present, the seam every caller uses to
    ask "is there a lager_box key to offer?".

    Faked at the seam rather than by patching os.path.exists: _ssh does a
    plain `import os`, so `_ssh.os.path` IS the stdlib posixpath module and
    patching it is process-global — on 3.14 pathlib.Path.exists() delegates
    to os.path.exists, so that patch silently rewrote the answer for every
    Path.exists() in the process (install's deploy-script check included).
    """
    return lambda key_path=KEY: (key_path if key_exists else None)


def _has_identity(argv):
    """True when argv offers the lager_box key."""
    return "-i" in argv and KEY in argv


class ProbeBoxIdentity(unittest.TestCase):
    """probe_box_identity answers "which identity should this command
    offer?" in at most two connections."""

    def _run(self, *, key_exists=True, results=None, **kwargs):
        calls = []

        def fake_run(cmd, **_kw):
            calls.append(list(cmd))
            return results[len(calls) - 1]

        with mock.patch.object(_ssh, "lager_box_key_if_present",
                               _fake_key_if_present(key_exists)), \
                mock.patch.object(_ssh.subprocess, "run", fake_run):
            identity, proc = _ssh.probe_box_identity("lagerdata@10.0.0.1", **kwargs)
        return identity, proc, calls

    def test_key_is_offered_and_returned_when_it_works(self):
        identity, _res, calls = self._run(results=[_proc(0, "ok")])
        self.assertEqual(identity, KEY)
        self.assertEqual(len(calls), 1, "one connection when the key works")
        self.assertTrue(_has_identity(calls[0]))

    def test_auth_failure_falls_back_to_default_identities(self):
        identity, proc, calls = self._run(
            results=[_proc(255, "", DENIED), _proc(0, "ok")],
        )
        self.assertIsNone(identity, "the box rejected the key")
        self.assertEqual(proc.returncode, 0, "the fallback attempt is what's returned")
        self.assertEqual(len(calls), 2)
        self.assertTrue(_has_identity(calls[0]))
        self.assertFalse(_has_identity(calls[1]))

    def test_no_key_file_means_no_dash_i_and_no_retry(self):
        # A box that has never had `lager ssh-setup` run against this
        # machine. Nothing to offer, and nothing to fall back to.
        identity, _res, calls = self._run(
            key_exists=False, results=[_proc(255, "", DENIED)],
        )
        self.assertIsNone(identity)
        self.assertEqual(len(calls), 1)
        self.assertFalse(_has_identity(calls[0]))

    def test_transport_failure_is_not_retried(self):
        # "no route to host" fails the same way twice, only slower.
        unreachable = _proc(255, "", "ssh: connect to host 10.0.0.1 port 22: No route to host")
        _identity, proc, calls = self._run(results=[unreachable])
        self.assertEqual(len(calls), 1)
        self.assertIn("No route to host", proc.stderr)

    def test_batch_mode_on_every_attempt(self):
        # BatchMode is what stops a box that authorizes nothing from hanging
        # on a password prompt it would refuse to honor anyway.
        _identity, _res, calls = self._run(
            results=[_proc(255, "", DENIED), _proc(255, "", DENIED)],
        )
        for argv in calls:
            self.assertIn("BatchMode=yes", argv)

    def test_keyed_attempt_isolates_the_key(self):
        """Without IdentitiesOnly, `-i` ADDS the key to a list that still
        holds the agent's keys and any ~/.ssh/config identity for the host,
        so the probe answers "can I reach this box at all?" — it returns the
        key as the working identity on a box where the key is not installed,
        and the keyless fallback can never fire. Observed on hardware: a box
        whose lager_box line had been deleted from authorized_keys probed
        healthy through the operator's own agent key."""
        _identity, _res, calls = self._run(results=[_proc(0, "ok")])
        self.assertIn("IdentitiesOnly=yes", calls[0])

    def test_keyless_attempt_does_not_isolate(self):
        # The fallback's whole job is to let the operator's own identities
        # through; IdentitiesOnly there would offer nothing at all.
        _identity, _res, calls = self._run(
            results=[_proc(255, "", DENIED), _proc(0, "ok")],
        )
        self.assertEqual(len(calls), 2)
        self.assertNotIn("IdentitiesOnly=yes", calls[1])

    def test_extra_args_are_passed_through(self):
        _identity, _res, calls = self._run(
            results=[_proc(0, "ok")],
            extra_args=("-o", "StrictHostKeyChecking=accept-new"),
        )
        self.assertIn("StrictHostKeyChecking=accept-new", calls[0])


class IdentityArgs(unittest.TestCase):
    def test_none_means_ssh_defaults(self):
        self.assertEqual(_ssh.ssh_identity_args(None), [])

    def test_path_becomes_dash_i(self):
        self.assertEqual(_ssh.ssh_identity_args("/k"), ["-i", "/k"])


class DefaultIdentities(unittest.TestCase):
    """default_identities_if_present puts back what `-i` took away: ssh's
    own identity files, in ssh's own order, minus the ones that do not
    exist (ssh warns about every named file it cannot load).

    Driven with real paths in a temp dir: the helper takes its candidates as
    a parameter, so nothing about the filesystem needs faking."""

    def test_keeps_only_the_files_that_exist_in_the_given_order(self):
        with tempfile.TemporaryDirectory() as td:
            rsa, ecdsa, ed25519 = (os.path.join(td, n) for n in ("id_rsa", "id_ecdsa", "id_ed25519"))
            for p in (rsa, ed25519):
                open(p, "w", encoding="utf-8").close()
            self.assertEqual(
                _ssh.default_identities_if_present([rsa, ecdsa, ed25519]),
                [rsa, ed25519],
            )

    def test_nothing_present_means_nothing_named(self):
        with tempfile.TemporaryDirectory() as td:
            self.assertEqual(
                _ssh.default_identities_if_present([os.path.join(td, "id_rsa")]), [],
            )

    def test_the_default_list_is_ssh_s_own(self):
        # ssh_config(5) IdentityFile, as `ssh -G` prints it on OpenSSH 8-10.
        # Order matters: it is what ssh would have tried unprompted, and a
        # box that authorizes two of these should see them in the same order.
        self.assertEqual(
            [os.path.basename(p) for p in _ssh.DEFAULT_IDENTITY_FILES],
            ["id_rsa", "id_ecdsa", "id_ecdsa_sk", "id_ed25519", "id_ed25519_sk"],
        )

    def test_the_default_list_is_expanded_for_dash_i(self):
        # ssh expands `~` in its own config but not in a -i argument.
        for p in _ssh.DEFAULT_IDENTITY_FILES:
            self.assertTrue(os.path.isabs(p), p)


class InteractiveSshIdentities(unittest.TestCase):
    """`lager ssh` hands the session to a human, so it cannot probe-and-retry
    the way install does: a retry would be a second interactive attempt. It
    offers everything at once instead -- lager_box first, then whichever of
    ssh's default identities exist -- so a box authorized on either connects.

    The bug this pins: with only `-i lager_box`, ssh dropped its default
    identity list, and a box authorized on the operator's id_ed25519 but not
    on lager_box refused `lager ssh` while a bare `ssh user@box` worked.

    Filesystem answers come through the two _ssh seams rather than os.path
    (see _fake_key_if_present), so the runner's own ~/.ssh never matters. The
    argv itself is built by _ssh.widened_identity_args, shared with the
    authorized_keys probe so the two cannot disagree about what -i does."""

    HOST = "lagerdata@10.0.0.1"
    DEFAULTS = [os.path.expanduser("~/.ssh/id_rsa"), os.path.expanduser("~/.ssh/id_ed25519")]

    def _argv(self, *, key_exists, defaults, command=()):
        calls = []

        def fake_call(argv, **_kw):
            calls.append(list(argv))
            return 0

        patches = [
            mock.patch.object(ssh_mod.subprocess, "call", fake_call),
            mock.patch.object(ssh_mod, "resolve_and_validate_box", lambda _ctx, _box: "10.0.0.1"),
            mock.patch.object(bs, "get_box_user", lambda _name: None),
            mock.patch.object(_ssh, "lager_box_key_if_present",
                              _fake_key_if_present(key_exists)),
            mock.patch.object(_ssh, "default_identities_if_present",
                              lambda: list(defaults)),
        ]
        for p in patches:
            p.start()
            self.addCleanup(p.stop)
        result = CliRunner().invoke(ssh_mod.ssh, ["--box", "10.0.0.1", *command])
        self.assertEqual(result.exit_code, 0, result.output)
        self.assertEqual(len(calls), 1, calls)
        return calls[0]

    @staticmethod
    def _identities(argv):
        """The -i values in argv, in the order ssh will see them."""
        return [argv[i + 1] for i, a in enumerate(argv) if a == "-i"]

    def test_lager_box_first_then_every_default_identity(self):
        argv = self._argv(key_exists=True, defaults=self.DEFAULTS)
        self.assertEqual(self._identities(argv), [KEY, *self.DEFAULTS])

    def test_every_identity_precedes_the_destination(self):
        # ssh stops reading options at the destination; an -i after it would
        # be sent to the box as part of the remote command.
        argv = self._argv(key_exists=True, defaults=self.DEFAULTS)
        self.assertEqual(argv[0], "ssh")
        self.assertEqual(argv[-1], self.HOST)
        last_i = max(i for i, a in enumerate(argv) if a == "-i")
        self.assertLess(last_i, argv.index(self.HOST))

    def test_no_lager_box_means_no_dash_i_at_all(self):
        # ssh offers its own defaults unprompted, so naming them would only
        # add noise; without the key this command is a bare `ssh user@host`,
        # exactly as before.
        argv = self._argv(key_exists=False, defaults=self.DEFAULTS)
        self.assertEqual(argv, ["ssh", self.HOST])

    def test_lager_box_alone_when_no_default_identity_exists(self):
        # A machine provisioned only by `lager ssh-setup`: the key is still
        # offered, so a box that authorizes only it connects without a
        # password prompt.
        argv = self._argv(key_exists=True, defaults=[])
        self.assertEqual(argv, ["ssh", "-i", KEY, self.HOST])

    def test_the_defaults_are_restored_not_isolated(self):
        # No IdentitiesOnly: ~/.ssh/config identities and agent keys stay on
        # offer after the named ones, as with a bare `ssh user@host`.
        argv = self._argv(key_exists=True, defaults=self.DEFAULTS)
        self.assertFalse(any("IdentitiesOnly" in a for a in argv), argv)

    def test_a_remote_command_still_follows_the_destination(self):
        argv = self._argv(key_exists=True, defaults=self.DEFAULTS,
                          command=["--", "ls", "-la", "/etc/lager"])
        self.assertEqual(argv[-2:], [self.HOST, "ls -la /etc/lager"])
        self.assertEqual(self._identities(argv), [KEY, *self.DEFAULTS])


class KeyRegistration(unittest.TestCase):
    """Installing the key and registering it are different acts.

    ssh-copy-id appends a line to authorized_keys OUTSIDE every manager's
    marker block. start_box.sh preserves such lines against its own rebuild,
    but a second key manager that rebuilds the file from its own source drops
    everything outside its markers — and start_box.sh then re-creates its
    block from /etc/lager/authorized_keys.d alone. A key never registered
    there does not come back, and on a box that also refuses passwords there
    is no way left to put it back. So every install path registers.
    """

    PUB = "ssh-ed25519 AAAATESTBLOB lager-box-access"

    def test_name_is_stable_and_filesystem_safe(self):
        name = _ssh.registered_key_name(user="ci", host="build-01")
        self.assertEqual(name, "lager-box-ci-build-01.pub")
        self.assertEqual(name, _ssh.registered_key_name(user="ci", host="build-01"))

    def test_name_sanitises_hostile_input(self):
        name = _ssh.registered_key_name(user="a/../b", host="x y;rm -rf")
        self.assertRegex(name, r"^lager-box-[A-Za-z0-9._-]+\.pub$")
        for bad in ("/", " ", ";"):
            self.assertNotIn(bad, name)

    def test_one_file_per_machine_so_rerun_replaces_not_accumulates(self):
        # A stale file would leave a superseded key authorized forever.
        self.assertNotIn(self.PUB, _ssh.registered_key_name(user="u", host="h"))
        cmd = _ssh.register_key_command(self.PUB, "lager-box-u-h.pub")
        self.assertIn(">", cmd, "truncating write, not an append")
        self.assertNotIn(">>", cmd)

    def test_command_writes_into_the_key_dir(self):
        cmd = _ssh.register_key_command(self.PUB, "lager-box-u-h.pub")
        self.assertIn(f"{_ssh.BOX_KEYS_DIR}/lager-box-u-h.pub", cmd)
        self.assertIn("mkdir -p", cmd)

    def test_tries_unprivileged_before_sudo(self):
        """On a plain Lager box the key directory belongs to the box and no
        sudo is wanted; the fallback exists for a box whose key manager made
        that directory root-owned, which it did on purpose."""
        cmd = _ssh.register_key_command(self.PUB, "lager-box-u-h.pub")
        plain = cmd.index("> ")
        sudo = cmd.index("sudo -n tee")
        self.assertLess(plain, sudo, "unprivileged write must be attempted first")
        self.assertIn("sudo -n", cmd, "and never sudo without -n: it must not prompt")

    def test_the_documented_grant_cannot_escape_the_key_dir(self):
        """Lager does not install this grant -- it prints it for a fleet that
        scopes sudo tightly to add through its own provisioning. Scoped to
        the filename shape, because a sudoers wildcard does not match '/'."""
        from cli.commands.box.ssh_setup import registration_sudoers_line
        line = registration_sudoers_line("boxuser")
        self.assertIn("NOPASSWD:", line)
        self.assertIn(f"{_ssh.BOX_KEYS_DIR}/lager-box-*.pub", line)
        self.assertTrue(line.startswith("boxuser "))
        # A directory-wide or bare-tee grant would let any file be written.
        self.assertFalse(line.rstrip().endswith("tee"))
        self.assertNotIn(f"tee {_ssh.BOX_KEYS_DIR} ", line)

    def test_failure_is_not_swallowed_by_the_trailing_chmod(self):
        # `A && B && C || true` would return 0 even when the write failed.
        # The `|| true` has to be confined to the chmod alone.
        cmd = _ssh.register_key_command(self.PUB, "lager-box-u-h.pub")
        self.assertTrue(cmd.rstrip().endswith("|| true; }"), cmd)
        self.assertNotIn("&& chmod 644 " + _ssh.BOX_KEYS_DIR, cmd)

    def test_pubkey_is_quoted_into_the_remote_shell(self):
        cmd = _ssh.register_key_command("blob; rm -rf ~", "lager-box-u-h.pub")
        self.assertNotIn("; rm -rf ~ ", cmd)
        self.assertIn("'blob; rm -rf ~'", cmd)

    def _register(self, *, rc=0, stderr="", pub=PUB):
        calls = []

        def fake_run(cmd, **_kw):
            calls.append(list(cmd))
            return _proc(rc, "", stderr)

        with mock.patch("builtins.open", mock.mock_open(read_data=pub)), \
                mock.patch.object(_ssh.subprocess, "run", fake_run):
            ok, detail = _ssh.register_lager_box_key("lagerdata@10.0.0.1")
        return ok, detail, calls

    def test_registers_over_the_key_so_it_costs_no_password(self):
        ok, _detail, calls = self._register()
        self.assertTrue(ok)
        self.assertTrue(_has_identity(calls[0]))
        self.assertIn("BatchMode=yes", calls[0])

    def test_failure_is_reported_not_raised(self):
        # The key is already installed and working by this point; a
        # read-only /etc/lager must not fail the whole command.
        ok, detail, _calls = self._register(rc=1, stderr="Permission denied")
        self.assertFalse(ok)
        self.assertIn("Permission denied", detail)

    def test_empty_pubkey_never_reaches_the_box(self):
        ok, detail, calls = self._register(pub="   \n")
        self.assertFalse(ok)
        self.assertIn("empty", detail)
        self.assertEqual(calls, [], "nothing sent")


class KeyInstalledOnBox(unittest.TestCase):
    """"Is the key on the box?" cannot be answered by logging in.

    A login proves only that SOME identity worked, and an operator whose
    ssh_config carries a `Host *` IdentityFile — a common fleet-management
    layout — has one for every host. Measured on hardware: a box that
    answered the auth probe rejected lager_box outright under
    `ssh -F /dev/null`, and because ssh-setup and update both gated their
    reinstall on that probe, neither could ever repair it.
    """

    PUB = "ssh-ed25519 AAAATESTBLOB lager-box-access"

    def _check(self, rc, *, pub=PUB, key_path=None, defaults=()):
        calls = []

        def fake_run(cmd, **_kw):
            calls.append(list(cmd))
            return _proc(rc)

        kwargs = {"key_path": key_path} if key_path is not None else {}
        # The probe now offers ssh's default identities after lager_box, so
        # the argv would otherwise depend on the runner's own ~/.ssh. Faked
        # at the _ssh seam, as the interactive tests above do.
        with mock.patch("builtins.open", mock.mock_open(read_data=pub)), \
                mock.patch.object(_ssh.shutil, "which", lambda _n: "/usr/bin/ssh"), \
                mock.patch.object(_ssh, "default_identities_if_present",
                                  lambda: list(defaults)), \
                mock.patch.object(_ssh.subprocess, "run", fake_run):
            return _ssh.key_installed_on_box("lagerdata@10.0.0.1", **kwargs), calls

    def test_greps_authorized_keys_for_the_blob_not_the_comment(self):
        # Comments drift -- the same key is `lager-box-access` locally and
        # whatever a key manager rendered it as on the box. The blob is the key.
        result, calls = self._check(0)
        self.assertIs(result, True)
        remote = calls[0][-1]
        self.assertIn("AAAATESTBLOB", remote)
        self.assertIn("authorized_keys", remote)
        self.assertNotIn("lager-box-access", remote)

    def test_grep_no_match_means_not_installed(self):
        self.assertIs(self._check(1)[0], False)

    def test_missing_authorized_keys_means_not_installed(self):
        # grep exits 2 for a missing file.
        self.assertIs(self._check(2)[0], False)

    def test_unreachable_box_is_unknown_not_absent(self):
        # 255 is ssh failing to get there; treating that as "not installed"
        # would trigger a pointless reinstall, and as "installed" would skip
        # a needed one. Neither is honest.
        self.assertIsNone(self._check(255)[0])

    def test_no_local_pubkey_is_unknown_and_asks_nothing(self):
        result, calls = self._check(0, pub="")
        self.assertIsNone(result)
        self.assertEqual(calls, [])

    def test_does_not_force_the_key_for_the_query_itself(self):
        # This is a question about the box's state, not about which
        # credential asks it -- any working identity is fine.
        _result, calls = self._check(0)
        self.assertNotIn("IdentitiesOnly=yes", calls[0])
        self.assertIn("BatchMode=yes", calls[0])

    def test_offers_the_key_so_the_query_can_authenticate_at_all(self):
        """Any identity is fine -- but one has to WORK for the probe to run.

        Found on hardware: on a machine whose default identities the box did
        not accept, and with lager_box not in the agent, ssh offered nothing
        usable. The probe got rc 255 and honestly returned None -- for a box
        it could have answered for, whose key was in fact installed. The
        operator's workaround was `ssh-add ~/.ssh/lager_box`, which should
        not be a prerequisite for asking a question about the box.

        lager_box is named FIRST and ssh's own defaults after it, so this
        does not contradict the test above: IdentitiesOnly is still not set,
        and any other working credential is still accepted. Naming lager_box
        alone would not have been enough -- see
        test_the_operators_own_identities_stay_on_offer.
        """
        import tempfile
        with tempfile.NamedTemporaryFile(suffix="_key") as key:
            _result, calls = self._check(0, key_path=key.name)
            self.assertIn("-i", calls[0])
            self.assertEqual(calls[0][calls[0].index("-i") + 1], key.name)
            self.assertNotIn("IdentitiesOnly=yes", calls[0])

    def test_a_missing_private_key_is_not_offered(self):
        """`-i` at a path that does not exist makes ssh noisier, not better."""
        _result, calls = self._check(0, key_path="/nonexistent/lager_box",
                                     defaults=["/home/op/.ssh/id_rsa"])
        self.assertNotIn("-i", calls[0],
                         "with no lager_box to prefer, name nothing and let "
                         "ssh use its own list")

    def test_the_operators_own_identities_stay_on_offer(self):
        """`-i` REPLACES ssh's default identity list; it does not add to it.

        Confirmed with `ssh -F /dev/null -G`: a bare connection offers
        id_rsa, id_ecdsa, id_ed25519 and their -sk variants, while naming any
        identity leaves exactly that one. So a lone `-i lager_box` withdrew
        every key the operator had installed themselves, and this probe --
        which needs only SOME working credential -- could not authenticate to
        a box authorized on one of them. It returned None, "could not ask",
        for exactly the box `lager ssh-setup` exists to repair.

        That is worse than it sounds, because both callers read None as "do
        not fail": `lager update` reports "SSH key installed successfully" on
        it, and ssh-setup skips its post-install verification. The check
        written to catch a silent no-op was itself silently skipped.
        """
        import tempfile
        defaults = ["/home/op/.ssh/id_rsa", "/home/op/.ssh/id_ed25519"]
        with tempfile.NamedTemporaryFile(suffix="_key") as key:
            _result, calls = self._check(0, key_path=key.name, defaults=defaults)
            offered = [calls[0][i + 1]
                       for i, a in enumerate(calls[0]) if a == "-i"]
            self.assertEqual(
                offered, [key.name, *defaults],
                "lager_box keeps precedence, with the operator's own "
                "identities restored after it")


def _unreachable_ssh(*_a, **_kw):
    """Stand in for every outbound ssh in this test.

    The "couldn't tell" path deliberately goes on to TRY the key, which means
    a real connection attempt. Without this stub the test waits out a connect
    timeout against an unroutable address -- a slow, network-dependent unit
    test.

    Returns a FAILED process rather than raising: rc 255 with ssh's own
    wording is what the code under test is written to handle, and raising
    OSError instead just escapes the command as an unhandled exception,
    which tests nothing about the branch we care about.
    """
    return subprocess.CompletedProcess(
        args=_a[0] if _a else [], returncode=255,
        stdout='', stderr='ssh: connect to host port 22: Network is unreachable')


class CallersHonourTheThreeOutcomeContract(unittest.TestCase):
    """None means "couldn't tell" and must not be read as "not installed".

    The probe's docstring is explicit about this, and it matters because the
    two readings have opposite repairs: "not installed" triggers a reinstall,
    "couldn't tell" should just try the key.

    Reported from a bench: `lager update --check` exited 2 with "SSH key not
    configured for this box" IMMEDIATELY after `lager ssh-setup` reported
    success -- on a box where the key really was installed (present twice in
    authorized_keys and registered under /etc/lager/authorized_keys.d). The
    probe had returned None because it could not authenticate to ask; the
    caller's bare truthiness test collapsed that into False.
    """

    def _check_run(self, probe_result, *, key_file_exists=True):
        """Drive `lager update --check` with the probe forced to *probe_result*.

        Whether the local key file exists is set up as a REAL file under a
        temporary HOME, not by patching os.path -- that is process-global and
        on 3.14+ rewrites every pathlib.Path.exists()
        (test_no_global_os_path_patches.py enforces this).

        It has to be controlled at all because the gate is
        ``os.path.exists(key_file) and <probe>``: on a host without
        ~/.ssh/lager_box it short-circuits and the probe is never consulted.
        Inheriting that from the machine made these tests pass on a laptop
        that happened to have the key and fail in CI -- testing nothing in
        either case.
        """
        import importlib
        import tempfile
        from click.testing import CliRunner
        update_mod = importlib.import_module('cli.commands.utility.update')

        with tempfile.TemporaryDirectory() as home:
            if key_file_exists:
                ssh_dir = os.path.join(home, '.ssh')
                os.makedirs(ssh_dir, exist_ok=True)
                with open(os.path.join(ssh_dir, 'lager_box'), 'w') as fh:
                    fh.write('PRIVATE KEY PLACEHOLDER\n')
            with mock.patch.dict(os.environ,
                                 {'HOME': home, 'USERPROFILE': home}), \
                 mock.patch.object(update_mod, 'resolve_and_validate_box',
                                   return_value='192.0.2.10'), \
                 mock.patch.object(update_mod, 'get_box_user',
                                   return_value='lagerdata'), \
                 mock.patch.object(update_mod, 'key_installed_on_box',
                                   return_value=probe_result), \
                 mock.patch.object(update_mod.subprocess, 'run',
                                   side_effect=_unreachable_ssh), \
                 mock.patch.object(
                     update_mod.subprocess, 'check_output',
                     side_effect=subprocess.CalledProcessError(255, 'ssh')):
                return CliRunner().invoke(
                    update_mod.update, ['--box', 'testbox', '--check'],
                    catch_exceptions=False)

    def test_a_definite_no_still_reports_the_key_is_not_configured(self):
        """False is a real answer and must keep its existing behaviour."""
        result = self._check_run(False)
        self.assertEqual(result.exit_code, 2)
        self.assertIn('SSH key', result.output)

    def test_couldnt_tell_still_takes_the_key_setup_path(self):
        """None must NOT be waved through as "the key works".

        Measured on a fleet: a box with no key cannot authenticate at all, so
        absence arrives as None far more often than as False -- False needs
        some OTHER identity to log in and grep to then miss. Treating None as
        "proceed" therefore swallows the ordinary "this box has no key yet"
        case. It was observed reporting "SSH key works" about a box that never
        authenticated, dropping --check from exit 2 to 1, replacing the
        actionable message with a bare Permission denied several steps later,
        and removing the only path that offers to install a key.

        The original defect -- a WORKING key reported missing -- is fixed in
        the probe itself, which now offers the key to its own SSH. With that,
        a box that has the key answers True.
        """
        result = self._check_run(None)
        self.assertEqual(result.exit_code, 2, f'output:\n{result.output}')
        self.assertIn('SSH key not configured', result.output)

    def test_couldnt_tell_does_not_claim_the_key_works(self):
        """The claim that was the opposite of the truth."""
        result = self._check_run(None)
        self.assertNotIn('SSH key works', result.output)

    def test_couldnt_tell_says_the_box_did_not_answer(self):
        """False and None take the same path but are not the same claim."""
        result = self._check_run(None)
        self.assertIn('the box did not answer the probe', result.output)

    def test_a_definite_no_does_not_get_the_unreachable_note(self):
        result = self._check_run(False)
        self.assertNotIn('the box did not answer the probe', result.output)

    def test_a_confirmed_key_proceeds_past_the_setup_path(self):
        """True is the only value that may skip key setup."""
        result = self._check_run(True)
        self.assertNotIn('SSH key not configured', result.output)

    def test_no_local_key_file_takes_the_setup_path_without_probing(self):
        """Nothing to offer means nothing to confirm; do not ask the box."""
        result = self._check_run(True, key_file_exists=False)
        self.assertEqual(result.exit_code, 2)
        self.assertIn('SSH key not configured', result.output)
        self.assertNotIn('the box did not answer the probe', result.output)

    def test_no_call_site_reads_the_probe_with_bare_truthiness(self):
        """Which comparison is right depends on the site; truthiness never is.

        The pre-flight gate wants `is True` -- only a confirmed key may skip
        setup. The post-copy check a few lines above wants `is not False`,
        because ssh-copy-id already succeeded there and an unverifiable probe
        should not undo it. Both are explicit; bare truthiness silently means
        `is True` and reads as if no decision was made.
        """
        src = (pathlib.Path(_ssh.__file__).resolve().parents[3]
               / 'cli' / 'commands' / 'utility' / 'update.py').read_text()
        for line in src.splitlines():
            stripped = line.strip()
            if 'key_installed_on_box(' not in line or stripped.startswith('#'):
                continue
            if 'import' in line or stripped.startswith('key_installed_on_box'):
                continue
            self.assertTrue(
                ('is True' in line or 'is not False' in line
                 or stripped.endswith('=  (') or '=' in stripped.split('(')[0]),
                f'call site reads the three-outcome result loosely: {stripped}')


class DeployScriptKeyCheck(unittest.TestCase):
    """The deploy script asks the same question the CLI does, the same way.

    It used to decide "is SSH set up?" by connecting, and fell through to a
    bare `ssh <box> echo test` when the keyed attempt failed. On a machine
    with an ssh_config `Host *` IdentityFile that bare probe always
    succeeds, so the script reported "Passwordless SSH already configured"
    and skipped generating, copying, and registering the key — on hardware,
    an install that reported success and left the box without a lager_box
    key at all.
    """

    @classmethod
    def setUpClass(cls):
        from pathlib import Path
        import cli
        cls.script = (Path(cli.__file__).parent / "deployment" / "scripts"
                      / "setup_and_deploy_box.sh").read_text()

    def _probe_block(self):
        start = self.script.index('print_info "Testing existing SSH configuration')
        return self.script[start:self.script.index("\nfi", start)]

    def test_it_greps_authorized_keys_rather_than_connecting(self):
        block = self._probe_block()
        self.assertIn("grep -qF", block)
        self.assertIn("authorized_keys", block)

    def test_no_bare_reachability_fallback(self):
        # `elif ssh ... "echo 'test'"` is the exact shape that made an
        # install skip key setup on a box that had no lager_box key.
        block = self._probe_block()
        self.assertNotIn("elif ssh", block)
        self.assertNotIn("echo 'test'", block)

    def test_missing_local_pubkey_means_set_it_up(self):
        # A first install has no key yet; the guard must not read an empty
        # blob as "already authorized".
        block = self._probe_block()
        self.assertIn('[ -n "$KEY_BLOB" ]', block)
        self.assertIn("NEEDS_SSH_SETUP=true", block)


class ConnectionPoolIdentity(unittest.TestCase):
    """The pool has to carry the identity too. ControlMaster=auto silently
    opens a fresh connection when the socket is gone, and that one
    authenticates for real."""

    def _pool(self):
        pool = ssh_utils.SSHConnectionPool.__new__(ssh_utils.SSHConnectionPool)
        pool.control_dir = ssh_utils.Path("/tmp/lager-test-control")
        pool._identities = {}
        return pool

    def _ensure(self, pool, results, **kwargs):
        """Drive ensure_connection with `results` for [check, start, start...].

        The master start hands ssh a real file for stderr rather than a pipe,
        so the fake writes there like ssh would.
        """
        calls = []
        kwargs_seen = []

        def fake_run(cmd, **kw):
            calls.append(list(cmd))
            kwargs_seen.append(kw)
            result = results[len(calls) - 1]
            errf = kw.get("stderr")
            if hasattr(errf, "write") and result.stderr:
                errf.write(result.stderr)
            return result

        with mock.patch.object(ssh_utils.subprocess, "run", fake_run), \
                mock.patch.object(ssh_utils.time, "sleep", lambda _s: None):
            ok = pool.ensure_connection("10.0.0.1", "lagerdata", **kwargs)
        self._kwargs_seen = kwargs_seen
        return ok, calls

    def test_master_offers_the_key_and_options_re_offer_it(self):
        pool = self._pool()
        with mock.patch.object(ssh_utils, "_auto_identity_candidates", return_value=[KEY, None]):
            ok, calls = self._ensure(pool, [_proc(1), _proc(0)])
        self.assertTrue(ok)
        self.assertTrue(_has_identity(calls[1]), "master start offers the key")
        self.assertTrue(_has_identity(pool.get_ssh_options("10.0.0.1")))

    def test_master_retries_without_the_key_when_rejected(self):
        pool = self._pool()
        with mock.patch.object(ssh_utils, "_auto_identity_candidates", return_value=[KEY, None]):
            ok, calls = self._ensure(pool, [_proc(1), _proc(255, "", DENIED), _proc(0)])
        self.assertTrue(ok)
        self.assertEqual(len(calls), 3)
        self.assertFalse(_has_identity(calls[2]))
        self.assertIsNone(pool.identity_for("10.0.0.1"))
        self.assertNotIn("-i", pool.get_ssh_options("10.0.0.1"))

    def test_master_does_not_retry_a_transport_failure(self):
        pool = self._pool()
        unreachable = _proc(255, "", "ssh: connect to host 10.0.0.1 port 22: Connection timed out")
        with mock.patch.object(ssh_utils, "_auto_identity_candidates", return_value=[KEY, None]):
            ok, calls = self._ensure(pool, [_proc(1), unreachable])
        self.assertFalse(ok)
        self.assertEqual(len(calls), 2, "check + one doomed master start")

    def test_explicit_identity_is_honored_over_auto_detection(self):
        # A caller that already probed passes its answer; None means "this
        # box does not take the key", and must not be re-derived.
        pool = self._pool()
        with mock.patch.object(ssh_utils, "_auto_identity_candidates", return_value=[KEY, None]):
            ok, calls = self._ensure(pool, [_proc(1), _proc(0)], identity_file=None)
        self.assertTrue(ok)
        self.assertFalse(_has_identity(calls[1]))

    def test_no_identity_learned_means_no_dash_i_in_options(self):
        pool = self._pool()
        self.assertNotIn("-i", pool.get_ssh_options("10.0.0.1"))

    def test_master_stderr_is_a_file_not_a_pipe(self):
        """`ssh -fNM` daemonizes without closing its inherited descriptors,
        so it holds the write end of a pipe open for its whole
        ControlPersist life. Reading that pipe blocks until the timeout —
        every successful master start would become a 15s hang and a False
        return, silently disabling multiplexing everywhere."""
        pool = self._pool()
        with mock.patch.object(ssh_utils, "_auto_identity_candidates", return_value=[None]):
            ok, calls = self._ensure(pool, [_proc(1), _proc(0)])
        self.assertTrue(ok)
        start_kwargs = self._kwargs_seen[1]
        self.assertNotIn("capture_output", start_kwargs)
        self.assertNotEqual(start_kwargs.get("stderr"), ssh_utils.subprocess.PIPE)
        self.assertTrue(hasattr(start_kwargs.get("stderr"), "write"),
                        "stderr must be a real file object")


class _CommandCase(unittest.TestCase):
    """Drives install/uninstall over a faked SSH transport.

    ``subprocess.run`` is patched on the module object itself, so the probe
    in cli.commands.box._ssh sees the fake too.
    """

    def _lock_patches(self):
        return [
            mock.patch.object(bs, "acquire_box_lock", return_value=("acquired", {})),
            mock.patch.object(bs, "release_box_lock", return_value=True),
            mock.patch.object(bs, "get_lock_holder", return_value="test-holder"),
            mock.patch.object(bs, "HeartbeatThread", return_value=mock.Mock()),
        ]

    def _ssh_calls(self, calls):
        return [argv for argv in calls if argv and argv[0] == "ssh"]


class InstallOffersTheKey(_CommandCase):
    def _install(self, *, key_exists=True, key_accepted=True):
        calls = []

        def fake_run(cmd, **_kw):
            cmd = list(cmd) if isinstance(cmd, (list, tuple)) else [cmd]
            calls.append(cmd)
            if cmd and cmd[0] != "ssh":
                return _proc(0)  # the deploy script
            if _has_identity(cmd) and not key_accepted:
                return _proc(255, "", DENIED)
            # Report the sudoers grant as not yet installed, so the
            # interactive `ssh -t` bootstrap runs and is covered too.
            if install_mod.BOXCFG_SUDOERS_MARKER in cmd[-1]:
                return _proc(1)
            return _proc(0, "0.36.2\n")

        patches = self._lock_patches() + [
            mock.patch.object(install_mod.subprocess, "run", fake_run),
            # Both bindings: probe_box_identity resolves the seam through
            # _ssh's globals, but install imports the name directly.
            mock.patch.object(_ssh, "lager_box_key_if_present",
                              _fake_key_if_present(key_exists)),
            mock.patch.object(install_mod, "lager_box_key_if_present",
                              _fake_key_if_present(key_exists)),
        ]
        for p in patches:
            p.start()
            self.addCleanup(p.stop)
        result = CliRunner().invoke(install_mod.install, ["--ip", "10.0.0.1", "--yes"])
        return result, self._ssh_calls(calls)

    def test_every_ssh_call_offers_the_key(self):
        result, calls = self._install()
        self.assertEqual(result.exit_code, 0, result.output)
        self.assertGreater(len(calls), 1, "sanity: install talked to the box")
        for argv in calls:
            self.assertTrue(_has_identity(argv), argv)

    def test_no_key_file_leaves_every_call_bare(self):
        # A fresh box reachable only by the operator's own key: -i would
        # suppress the very identities that work.
        result, calls = self._install(key_exists=False)
        self.assertEqual(result.exit_code, 0, result.output)
        self.assertTrue(calls, "sanity: install talked to the box")
        for argv in calls:
            self.assertNotIn("-i", argv, argv)


class InstallHasNoPasswordFallback(_CommandCase):
    """A hardened box sets PasswordAuthentication no, so ssh never sent the
    password install had just asked for — and then reported a password
    failure for what was an identity failure."""

    def _install_rejected(self, *, decline=False, provision=None):
        """Drive install against a box that authorizes nothing.

        `provision` replaces the key-setup helper; None means "the box
        refuses the key too", which is what a box with
        PasswordAuthentication no does.
        """
        calls = []

        def fake_run(cmd, **_kw):
            cmd = list(cmd) if isinstance(cmd, (list, tuple)) else [cmd]
            calls.append(cmd)
            # The deploy script; only SSH is being refused here.
            if cmd and cmd[0] != "ssh":
                return _proc(0)
            return _proc(255, "", DENIED)

        def refuses(dest, **_kw):
            raise install_mod.LagerError(f"ssh-copy-id to {dest} failed.")

        patches = self._lock_patches() + [
            mock.patch.object(install_mod.subprocess, "run", fake_run),
            mock.patch.object(_ssh, "lager_box_key_if_present",
                              _fake_key_if_present(True)),
            mock.patch.object(install_mod, "lager_box_key_if_present",
                              _fake_key_if_present(True)),
            mock.patch.object(install_mod, "provision_lager_box_key",
                              provision or refuses),
        ]
        for p in patches:
            p.start()
            self.addCleanup(p.stop)
        args = ["--ip", "10.0.0.1"] + ([] if decline else ["--yes"])
        result = CliRunner().invoke(install_mod.install, args, input="n\n")
        return result, self._ssh_calls(calls)

    def test_it_sets_the_key_up_rather_than_dead_ending(self):
        # Install used to stop and tell you to run `lager ssh-setup` first.
        # The password it would have asked for is the same one install needs,
        # so it does that work itself now.
        provisioned = []
        result, _calls = self._install_rejected(
            provision=lambda dest, **_kw: provisioned.append(dest) or False)
        self.assertEqual(provisioned, ["lagerdata@10.0.0.1"])
        self.assertEqual(result.exit_code, 0, result.output)

    def test_declining_still_names_the_command_that_fixes_it(self):
        result, _calls = self._install_rejected(decline=True)
        self.assertNotEqual(result.exit_code, 0)
        self.assertIn("lager ssh-setup", result.output)

    def test_a_setup_failure_keeps_its_own_guidance(self):
        # The provisioning error is raised inside install's broad
        # `except Exception`, which would re-wrap it as a generic
        # "SSH connectivity check failed" and discard what it said.
        result, _calls = self._install_rejected()
        self.assertNotEqual(result.exit_code, 0)
        self.assertIn("ssh-copy-id", result.output)
        self.assertNotIn("SSH connectivity check failed", result.output)

    def test_no_password_prompt_is_ever_attempted(self):
        _result, calls = self._install_rejected()
        for argv in calls:
            self.assertNotIn("NumberOfPasswordPrompts=1", argv, argv)

    def test_it_probed_with_the_key_before_giving_up(self):
        # Offering to install the key is only honest if it really was tried.
        _result, calls = self._install_rejected()
        self.assertTrue(any(_has_identity(argv) for argv in calls))
        self.assertTrue(any(not _has_identity(argv) for argv in calls),
                        "and the default identities were tried too")


class UninstallOffersTheKey(_CommandCase):
    def _uninstall(self, *, key_exists=True, key_accepted=True):
        calls = []

        def fake_run(cmd, **_kw):
            cmd = list(cmd) if isinstance(cmd, (list, tuple)) else [cmd]
            calls.append(cmd)
            remote = cmd[-1]
            if _has_identity(cmd) and not key_accepted:
                return _proc(255, "", DENIED)
            if remote.startswith("cat ") and uninstall_mod._PRIV_RESULTS_PATH in remote:
                return _proc(0, "lock_state=OK\n")
            return _proc(0, "ok")

        # Force the un-multiplexed path so the command's own identity
        # threading — not the pool's — is what is under test.
        pool = mock.Mock()
        pool.ensure_connection.return_value = False

        patches = self._lock_patches() + [
            mock.patch.object(uninstall_mod.subprocess, "run", fake_run),
            mock.patch.object(uninstall_mod, "get_ssh_connection_pool", return_value=pool),
            mock.patch.object(uninstall_mod, "get_box_name_by_ip", return_value=None),
            mock.patch.object(_ssh, "lager_box_key_if_present",
                              _fake_key_if_present(key_exists)),
        ]
        for p in patches:
            p.start()
            self.addCleanup(p.stop)
        result = CliRunner().invoke(
            uninstall_mod.uninstall, ["--ip", "10.0.0.1", "--yes", "--keep-config"],
        )
        return result, self._ssh_calls(calls), pool

    def test_every_teardown_command_offers_the_key(self):
        result, calls, _pool = self._uninstall()
        self.assertEqual(result.exit_code, 0, result.output)
        self.assertGreater(len(calls), 5, "sanity: the teardown ran")
        for argv in calls:
            self.assertTrue(_has_identity(argv), argv)

    def test_the_probe_result_is_handed_to_the_pool(self):
        _result, _calls, pool = self._uninstall()
        self.assertEqual(
            pool.ensure_connection.call_args.kwargs.get("identity_file"), KEY,
        )

    def test_a_box_that_rejects_the_key_keeps_working(self):
        result, calls, _pool = self._uninstall(key_accepted=False)
        self.assertEqual(result.exit_code, 0, result.output)
        teardown = [a for a in calls if a[-1] != "echo ok"]
        self.assertTrue(teardown, "sanity: the teardown ran")
        for argv in teardown:
            self.assertNotIn("-i", argv, argv)

    def test_no_key_file_leaves_every_call_bare(self):
        result, calls, _pool = self._uninstall(key_exists=False)
        self.assertEqual(result.exit_code, 0, result.output)
        for argv in calls:
            self.assertNotIn("-i", argv, argv)


class UninstallDeregisters(_CommandCase):
    """--all strips the authorized_keys line. Without also removing the
    registration, --keep-config preserves /etc/lager and the next
    start_box.sh sync republishes the key uninstall just removed."""

    def test_all_removes_the_registered_pubkey_first(self):
        calls = []

        def fake_run(cmd, **_kw):
            cmd = list(cmd) if isinstance(cmd, (list, tuple)) else [cmd]
            calls.append(cmd)
            remote = cmd[-1]
            if remote.startswith("cat ") and uninstall_mod._PRIV_RESULTS_PATH in remote:
                return _proc(0, "lock_state=OK\n")
            return _proc(0, "ok")

        pool = mock.Mock()
        pool.ensure_connection.return_value = False
        patches = self._lock_patches() + [
            mock.patch.object(uninstall_mod.subprocess, "run", fake_run),
            mock.patch.object(uninstall_mod, "get_ssh_connection_pool", return_value=pool),
            mock.patch.object(uninstall_mod, "get_box_name_by_ip", return_value=None),
            mock.patch.object(_ssh, "lager_box_key_if_present",
                              _fake_key_if_present(True)),
        ]
        for p in patches:
            p.start()
            self.addCleanup(p.stop)
        result = CliRunner().invoke(
            uninstall_mod.uninstall,
            ["--ip", "10.0.0.1", "--yes", "--keep-config", "--all"],
        )
        self.assertEqual(result.exit_code, 0, result.output)

        remotes = [c[-1] for c in self._ssh_calls(calls)]
        dereg = [i for i, r in enumerate(remotes)
                 if uninstall_mod.BOX_KEYS_DIR in r and r.startswith("rm -f")]
        strip = [i for i, r in enumerate(remotes) if "authorized_keys" in r and "grep -vF" in r]
        self.assertTrue(dereg, f"no de-registration in {remotes}")
        self.assertTrue(strip, "sanity: the authorized_keys strip still runs")
        self.assertLess(dereg[0], strip[0], "de-register before stripping")

    def test_it_names_only_this_machines_file(self):
        # A glob would revoke every other operator's registration.
        cmd = f"rm -f {uninstall_mod.BOX_KEYS_DIR}/{uninstall_mod.registered_key_name()}"
        self.assertNotIn("*", cmd)

if __name__ == "__main__":
    unittest.main()
