#!/usr/bin/env python3
# Copyright 2024-2026 Lager Data
# SPDX-License-Identifier: Apache-2.0
"""
Unit tests for `lager update`'s sparse-checkout flatten (`box/` -> root) and
for the docker-build hash that decides whether the cached image is wiped.

Both are shell snippets that normally run over SSH. We don't spin up SSH:
the snippets are generated by plain functions, so each test runs the real
shipped string through `bash` against a throwaway directory tree with `HOME`
pointed at it. `~/box` therefore resolves inside the temp dir and the real
home directory is never touched.

The regression that motivated these tests: the flatten used `cp -rf box/* .`,
which is *additive*. It overwrote changed files but never removed ones the
new tree no longer contained, so a file deleted upstream persisted on every
box indefinitely and was baked into the runtime image. Because the flatten
then deleted the tracked source, the resulting tree was untracked and neither
`git checkout -f` nor `git reset --hard` could clean it up.
"""

import os
import shutil
import subprocess
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))))

from cli.commands.utility.update import (  # noqa: E402
    _flatten_shell_cmd,
    _build_hash_shell_cmd,
    _BUILD_HASH_INPUTS,
    _BUILD_HASH_SOURCE_DIRS,
)


def _have(*tools):
    return all(shutil.which(t) for t in tools)


# The build-hash snippet needs GNU coreutils (`sha256sum`, `sort -z`).
# macOS ships neither, so those tests skip locally and run on Linux CI.
_HAS_GNU_HASH_TOOLS = _have('sha256sum', 'sort', 'xargs', 'find')


class FlattenShellTestBase(unittest.TestCase):
    """Runs the shipped flatten snippet against a temp tree."""

    def setUp(self):
        self.home = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.home, ignore_errors=True)
        self.boxroot = os.path.join(self.home, 'box')
        os.makedirs(self.boxroot)

    def touch(self, *parts):
        path = os.path.join(self.boxroot, *parts)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w') as handle:
            handle.write('x')
        return path

    def mkdir(self, *parts):
        path = os.path.join(self.boxroot, *parts)
        os.makedirs(path, exist_ok=True)
        return path

    def run_flatten(self):
        env = dict(os.environ, HOME=self.home)
        return subprocess.run(
            ['bash', '-c', _flatten_shell_cmd()],
            env=env, capture_output=True, text=True,
        )

    def exists(self, *parts):
        return os.path.exists(os.path.join(self.boxroot, *parts))


class DeletedUpstreamFilesAreRemoved(FlattenShellTestBase):
    """The core regression. A file that a previous flatten left at the root
    but that the new `box/` tree no longer contains must not survive."""

    def setUp(self):
        super().setUp()
        # Previous flatten's output, including files since deleted upstream.
        self.touch('lager', 'http_handlers', 'ssh_handler.py')
        self.touch('lager', 'util.py')
        self.touch('lager', 'mcp', 'tools', 'python_run.py')
        self.touch('lager', 'mcp', 'tools', 'pip_tools.py')
        self.touch('lager', 'box_http_server.py')
        # The freshly pulled tree: none of the deleted files are present.
        self.touch('box', 'lager', 'box_http_server.py')
        self.touch('box', 'lager', 'mcp', 'tools', 'control.py')

    def test_flatten_succeeds(self):
        self.assertEqual(self.run_flatten().returncode, 0)

    def test_deleted_handler_is_removed(self):
        self.run_flatten()
        self.assertFalse(self.exists('lager', 'http_handlers', 'ssh_handler.py'))

    def test_deleted_top_level_module_is_removed(self):
        self.run_flatten()
        self.assertFalse(self.exists('lager', 'util.py'))

    def test_deleted_execute_capable_mcp_tools_are_removed(self):
        self.run_flatten()
        self.assertFalse(self.exists('lager', 'mcp', 'tools', 'python_run.py'))
        self.assertFalse(self.exists('lager', 'mcp', 'tools', 'pip_tools.py'))

    def test_surviving_files_are_still_present(self):
        self.run_flatten()
        self.assertTrue(self.exists('lager', 'box_http_server.py'))
        self.assertTrue(self.exists('lager', 'mcp', 'tools', 'control.py'))

    def test_flattened_tree_exactly_mirrors_source(self):
        """Not merely "the stale ones we knew about" — the whole subtree must
        match, which is what makes the docker build context trustworthy."""
        expected = set()
        src = os.path.join(self.boxroot, 'box', 'lager')
        for root, _dirs, files in os.walk(src):
            for name in files:
                expected.add(os.path.relpath(os.path.join(root, name), src))
        self.run_flatten()
        actual = set()
        dst = os.path.join(self.boxroot, 'lager')
        for root, _dirs, files in os.walk(dst):
            for name in files:
                actual.add(os.path.relpath(os.path.join(root, name), dst))
        self.assertEqual(expected, actual)


class RootLevelEntriesArePreserved(FlattenShellTestBase):
    """Only the top-level names `box/` provides may be touched. A blanket wipe
    of `~/box` would take out `.git` and the sparse-checked-out `cli/` the host
    CLI install depends on."""

    def setUp(self):
        super().setUp()
        self.touch('.git', 'HEAD')
        self.touch('cli', '__init__.py')
        self.touch('.gitignore')
        self.touch('box', 'lager', 'box_http_server.py')

    def test_git_dir_survives(self):
        self.run_flatten()
        self.assertTrue(self.exists('.git', 'HEAD'))

    def test_sparse_checked_out_cli_survives(self):
        self.run_flatten()
        self.assertTrue(self.exists('cli', '__init__.py'))

    def test_root_only_dotfile_survives(self):
        self.run_flatten()
        self.assertTrue(self.exists('.gitignore'))


class OverwriteAndDotglobBehaviour(FlattenShellTestBase):
    def setUp(self):
        super().setUp()
        self.touch('box', 'lager', 'box_http_server.py')

    def test_dotfiles_inside_box_are_moved(self):
        """`shopt -s dotglob`. Without it a hidden entry would be left behind
        in `box/`, and `rmdir` would then refuse to retire the directory."""
        self.touch('box', '.hidden')
        self.run_flatten()
        self.assertTrue(self.exists('.hidden'))
        self.assertFalse(self.exists('box'))

    def test_colliding_root_file_is_replaced(self):
        """Root and `box/` both carry a README.md; `box/`'s copy wins."""
        readme = self.touch('README.md')
        with open(readme, 'w') as handle:
            handle.write('root version')
        src = self.touch('box', 'README.md')
        with open(src, 'w') as handle:
            handle.write('box version')
        self.run_flatten()
        with open(os.path.join(self.boxroot, 'README.md')) as handle:
            self.assertEqual(handle.read(), 'box version')

    def test_move_does_not_nest_into_existing_directory(self):
        """`mv a b` puts `a` *inside* `b` when `b` is an existing directory.
        Removing the destination first is what prevents `~/box/lager/lager`."""
        self.touch('lager', 'stale.py')
        self.run_flatten()
        self.assertFalse(self.exists('lager', 'lager'))

    def test_source_directory_is_retired(self):
        self.run_flatten()
        self.assertFalse(self.exists('box'))


class DegenerateInputs(FlattenShellTestBase):
    def test_empty_box_dir_is_a_noop_not_a_wipe(self):
        """`nullglob`: an unmatched `box/*` must expand to nothing rather than
        to the literal string, which would make `$name` a bare `*`."""
        self.touch('lager', 'box_http_server.py')
        self.touch('.gitignore')
        self.mkdir('box')
        result = self.run_flatten()
        self.assertEqual(result.returncode, 0)
        self.assertTrue(self.exists('lager', 'box_http_server.py'))
        self.assertTrue(self.exists('.gitignore'))

    def test_absent_box_dir_is_a_noop(self):
        """Already-flat box: nothing to do, and nothing may be destroyed."""
        self.touch('lager', 'box_http_server.py')
        result = self.run_flatten()
        self.assertEqual(result.returncode, 0)
        self.assertTrue(self.exists('lager', 'box_http_server.py'))

    def test_missing_box_root_fails_rather_than_running_elsewhere(self):
        """`cd ~/box` must gate the whole snippet: if it fails, the loop must
        not run against whatever directory the shell happened to start in."""
        shutil.rmtree(self.boxroot)
        self.assertNotEqual(self.run_flatten().returncode, 0)


class FlattenSnippetInvariants(unittest.TestCase):
    """Guards on the shipped string for properties that are awkward to
    reproduce behaviourally."""

    def setUp(self):
        self.cmd = _flatten_shell_cmd()

    def test_uses_rmdir_so_a_partial_flatten_keeps_its_source(self):
        """`rmdir` only succeeds once every entry has moved. `rm -rf box`
        would delete the source a retry depends on after a partial failure."""
        self.assertIn('rmdir box', self.cmd)
        self.assertNotIn('rm -rf box;', self.cmd)
        self.assertNotIn('rm -rf box ', self.cmd)

    def test_nullglob_is_enabled(self):
        self.assertIn('nullglob', self.cmd)

    def test_dotglob_is_enabled(self):
        self.assertIn('dotglob', self.cmd)

    def test_expansions_are_quoted(self):
        """An unquoted `$name` would re-glob and, combined with a literal `*`
        from a failed expansion, turn the removal into `rm -rf ./*`."""
        self.assertIn('rm -rf "./$name"', self.cmd)
        self.assertIn('mv "$src" "./$name"', self.cmd)

    def test_does_not_use_additive_copy(self):
        """The regression guard: `cp -rf box/*` is what caused the bug."""
        self.assertNotIn('cp -rf', self.cmd)


@unittest.skipUnless(_HAS_GNU_HASH_TOOLS, 'GNU coreutils not available')
class BuildHashCoversSourceTree(unittest.TestCase):
    """A pure-Python change must invalidate the cached image. Before this,
    `_BUILD_HASH_INPUTS` held only the Dockerfile and requirements.txt, so
    `must_wipe_image` stayed false for source-only changes and correctness
    rested entirely on BuildKit's COPY cache."""

    def setUp(self):
        self.home = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.home, ignore_errors=True)
        self.src = os.path.join(self.home, 'box', 'lager')
        os.makedirs(os.path.join(self.src, 'docker'))
        self.write(os.path.join(self.src, 'docker', 'box.Dockerfile'), 'FROM python\n')
        self.write(os.path.join(self.src, 'box_http_server.py'), 'print(1)\n')
        self.write(os.path.join(self.src, 'handlers.py'), 'print(2)\n')

    def write(self, path, text):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w') as handle:
            handle.write(text)

    def hash(self):
        result = subprocess.run(
            ['bash', '-c', _build_hash_shell_cmd()],
            env=dict(os.environ, HOME=self.home),
            capture_output=True, text=True,
        )
        return result.stdout.strip()

    def test_source_dir_is_configured(self):
        self.assertIn('~/box/lager', _BUILD_HASH_SOURCE_DIRS)

    def test_dockerfile_still_configured(self):
        self.assertIn('~/box/lager/docker/box.Dockerfile', _BUILD_HASH_INPUTS)

    def test_produces_a_hash(self):
        self.assertRegex(self.hash(), r'^[0-9a-f]{64}$')

    def test_stable_across_runs(self):
        self.assertEqual(self.hash(), self.hash())

    def test_editing_a_source_file_changes_the_hash(self):
        before = self.hash()
        self.write(os.path.join(self.src, 'handlers.py'), 'print(3)\n')
        self.assertNotEqual(before, self.hash())

    def test_deleting_a_source_file_changes_the_hash(self):
        """The case the additive flatten used to hide: a file removed upstream
        must be visible to the hash, not silently equivalent."""
        before = self.hash()
        os.remove(os.path.join(self.src, 'handlers.py'))
        self.assertNotEqual(before, self.hash())

    def test_adding_a_source_file_changes_the_hash(self):
        before = self.hash()
        self.write(os.path.join(self.src, 'extra.py'), 'print(4)\n')
        self.assertNotEqual(before, self.hash())

    def test_renaming_a_source_file_changes_the_hash(self):
        """`sha256sum` prints the path, so a rename is not a no-op even though
        the file contents are unchanged."""
        before = self.hash()
        os.rename(os.path.join(self.src, 'handlers.py'),
                  os.path.join(self.src, 'renamed.py'))
        self.assertNotEqual(before, self.hash())

    def test_pycache_is_ignored(self):
        """Derived artifacts regenerated on the box must not wipe the image."""
        before = self.hash()
        self.write(os.path.join(self.src, '__pycache__', 'handlers.cpython-311.pyc'), 'junk')
        self.write(os.path.join(self.src, 'mcp', '__pycache__', 'x.cpython-311.pyc'), 'junk')
        self.assertEqual(before, self.hash())

    def test_stray_pyc_outside_pycache_is_ignored(self):
        before = self.hash()
        self.write(os.path.join(self.src, 'stray.pyc'), 'junk')
        self.assertEqual(before, self.hash())

    def test_empty_when_nothing_matches(self):
        shutil.rmtree(os.path.join(self.home, 'box'))
        self.assertEqual(self.hash(), '')


if __name__ == '__main__':
    unittest.main()
