# Copyright 2024-2026 Lager Data
# SPDX-License-Identifier: Apache-2.0

"""MCP guide resources — context the agent reads at session start."""

from __future__ import annotations

import json


def register(mcp):
    @mcp.resource("lager://guide/overview")
    def guide_overview() -> str:
        """What is Lager, how does it work, and what is a 'net'."""
        return (
            "# Lager — Hardware-in-the-Loop Test Platform\n"
            "\n"
            "A **Lager box** is a small Linux computer that sits next to your "
            "device-under-test (DUT).  It has physical connections to the DUT "
            "via instruments — power supplies, debug probes, logic analysers, "
            "protocol adapters (SPI/I2C/UART), USB hubs, GPIO, and more.\n"
            "\n"
            "Each physical connection is represented as a **net** — a named "
            "handle you use in code.  For example, `supply1` might be a power "
            "supply set to 3.3 V, `spi1` might be an SPI bus wired to a flash "
            "chip, and `uart1` might be the DUT's debug console.  Each net "
            "exposes a one-line `purpose` (*what does this wire do on the "
            "DUT?*) and optional `notes`.  Nets are grouped into **subsystems** "
            "(*Power tree*, *Flash subsystem*, *Debug*, ...) on the DUT.\n"
            "\n"
            "You interact with hardware through the **`lager` Python API**:\n"
            "\n"
            "```python\n"
            "from lager import Net, NetType\n"
            "\n"
            "psu = Net.get('supply1', type=NetType.PowerSupply)\n"
            "psu.set_voltage(3.3)\n"
            "psu.enable()\n"
            "```\n"
            "\n"
            "Scripts run **directly on the box** via `lager python`, so hardware "
            "calls are local with sub-millisecond latency — no network round "
            "trips between steps.\n"
        )

    @mcp.resource("lager://guide/workflow")
    def guide_workflow() -> str:
        """Recommended workflow: orient → discover → plan → write → run → analyse."""
        return (
            "# Recommended Test Workflow\n"
            "\n"
            "## 0. Orient (read this first)\n"
            "Read `lager://dut/overview.md` for a narrative briefing on the "
            "DUT: what this box tests, the MCU/peripherals, the subsystems, "
            "and which documents (schematics, datasheets) to fetch. If you "
            "need the structured shape instead, read `lager://dut/context` "
            "or call `discover_dut()`.\n"
            "\n"
            "**Schematics and datasheets are NOT stored on the box.** The "
            "DUT context advertises references with either a `url` or a "
            "`repo_path` (relative to your project, which is synced to the "
            "box when you run `lager python ... --box <box-ip>`). Open them "
            "with your own file tools — vision models analyse per-sheet "
            "PNG exports faster than full PDFs. Call "
            "`cite_schematic(net_name)` to get just the doc refs and page "
            "hints relevant to one net.\n"
            "\n"
            "## 0b. Rendering schematic / datasheet pages\n"
            "The box does not render anything — it only stores references. "
            "You render on your **own machine** using the synced repo file "
            "(`repo_path`).\n"
            "\n"
            "- Render **only** the `pages` range from the doc ref — never the "
            "whole PDF.\n"
            "- Prefer **PNGs** for schematics and scanned pages (vision models "
            "read per-sheet images far faster); for text-based specs, "
            "extracting the text for the page range is fine.\n"
            "- Recommended tool: **pymupdf** (`pip install pymupdf`). Or use "
            "the project's `tools/pdf_pages.py` helper for consistent naming "
            "and DPI.\n"
            "\n"
            "```python\n"
            "import fitz  # pymupdf\n"
            'doc = fitz.open("path/from/repo_path.pdf")\n'
            "mat = fitz.Matrix(3, 3)  # ~216 dpi; raise for dense schematics\n"
            "for i in range(START - 1, END):   # START/END from the doc ref's `pages`\n"
            '    doc[i].get_pixmap(matrix=mat).save(f"page_{i+1:03d}.png")\n'
            "```\n"
            "\n"
            "## 1. Discover\n"
            "Call `discover_bench()` to see what hardware is available: nets, "
            "instruments, and capabilities.  For details on a specific net, call "
            "`discover_bench(net_name)` — the response now includes the "
            "subsystem the net belongs to and any relevant doc refs.\n"
            "\n"
            "## 2. Plan\n"
            "Call `plan_firmware_test(firmware_description, test_goals)` with a "
            "description of what the firmware does and what you want to validate. "
            "It cross-references the bench's nets and their metadata to produce "
            "a structured test plan.\n"
            "\n"
            "## 3. Learn the API\n"
            "Read `lager://reference/{net_type}` for the Python API of the "
            "relevant net types (PowerSupply, UART, SPI, etc.).  Call "
            "`get_test_example(pattern)` to see a proven, runnable example "
            "script.  For anything not covered here — full method signatures, "
            "every net type, error handling — read the hosted docs listed in "
            "`lager://guide/docs` (start at "
            "https://docs.lagerdata.com/llms.txt).\n"
            "\n"
            "**Reading firmware logs?** RTT + `defmt-print` is the core debug "
            "workflow and has sharp edges (defmt bytes are binary, the stream "
            "never ends, status vs payload streams). Read "
            "`lager://guide/rtt-defmt` before trying to capture RTT logs. The "
            "short version, run from your shell:\n"
            "```\n"
            "timeout 15 lager debug <NET> gdbserver --box <box-ip> --rtt 2>/dev/null \\\n"
            "  | defmt-print -e build/app.elf\n"
            "```\n"
            "\n"
            "## 4. Write a Test File\n"
            "Author a Python test file locally using `from lager import Net, "
            "NetType`.  Write it like a normal Python program.  Use try/finally "
            "blocks to clean up hardware state.  Your full project is available "
            "on-box (dtest, SerialDevice, custom modules, etc.).\n"
            "\n"
            "## 5. Run\n"
            "Execution does not happen over MCP. Identify the box by the **IP "
            "address** you connected to this MCP server on "
            "(`http://<box-ip>:8100/mcp`) — local box names are arbitrary "
            "client-side aliases, so the IP is the only identifier you can rely "
            "on. `--box` accepts a raw IP directly, so no registration is "
            "needed:\n"
            "```\n"
            "# Run a single test file\n"
            "lager python path/to/test.py --box <box-ip>\n"
            "\n"
            "# ...or run a whole folder (its entrypoint must be main.py).\n"
            "# Everything in the folder is synced and importable, so you can\n"
            "# ship reusable helper modules alongside the test.\n"
            "lager python path/to/test_dir --box <box-ip>\n"
            "```\n"
            "This syncs your local project to the box and runs the script with "
            "full project context.  Output streams back to your terminal. "
            "(Optionally, `lager boxes add --name <name> --ip <box-ip>` "
            "registers a friendly alias — only useful for a stable name or a "
            "non-default SSH user.)\n"
            "\n"
            "## 6. Analyse & Iterate\n"
            "Review the CLI output.  If assertions fail or results are "
            "unexpected, adjust the script and re-run it with `lager python`.\n"
        )

    @mcp.resource("lager://guide/docs")
    def guide_docs() -> str:
        """Where to find the full, authoritative Lager documentation online."""
        return (
            "# Lager Documentation\n"
            "\n"
            "The resources and tools on this server are a curated subset for "
            "fast orientation. For complete API details, every net type, edge "
            "cases, and anything not covered here, read the hosted docs with "
            "your own web-fetch tool:\n"
            "\n"
            "- **Docs home:** https://docs.lagerdata.com\n"
            "- **Python SDK (the `lager.Net` API you write tests against):** "
            "https://docs.lagerdata.com/source/reference/python/overview\n"
            "- **CLI reference (`lager python`, `lager boxes`, `lager nets`, "
            "...):** https://docs.lagerdata.com/source/reference/cli\n"
            "- **Full page index for agents:** "
            "https://docs.lagerdata.com/llms.txt\n"
            "\n"
            "Fetch `llms.txt` first — it lists every page so you can discover "
            "what exists before opening specific pages.\n"
        )

    @mcp.resource("lager://guide/rtt-defmt")
    def guide_rtt_defmt() -> str:
        """How to capture RTT logs and decode defmt firmware logging.

        This is the single most important debug workflow: streaming RTT
        off the DUT and piping it through ``defmt-print``. Read this
        before trying to read RTT logs from defmt-based firmware.
        """
        return (
            "# Capturing RTT logs (and decoding defmt)\n"
            "\n"
            "RTT (Real-Time Transfer) is the low-latency log channel most "
            "embedded firmware uses to print over the debug probe. There are "
            "two flavours of RTT payload and you must handle them "
            "differently:\n"
            "\n"
            "- **Plain-text RTT** — the firmware writes human-readable "
            "strings. You can print the bytes directly.\n"
            "- **defmt RTT** — the firmware uses the `defmt` framework (very "
            "common in embedded Rust). The bytes are a **compressed binary "
            "format**, NOT text. `bytes.decode()` or printing them yields "
            "garbage. They MUST be decoded by `defmt-print` using the **exact "
            "matching firmware ELF**.\n"
            "\n"
            "If you ever see RTT output that looks like binary noise, the "
            "firmware is almost certainly using defmt — switch to the "
            "`defmt-print` pipe below.\n"
            "\n"
            "## Canonical pattern (do this) — CLI pipe on your machine\n"
            "Run this from your **own shell** (not over MCP, not inside a "
            "`lager python` script). `defmt-print` runs locally where your "
            "build artifacts (the `.elf`) live:\n"
            "\n"
            "```bash\n"
            "lager debug <NET> gdbserver --box <box-ip> --rtt 2>/dev/null \\\n"
            "  | defmt-print -e path/to/app.elf\n"
            "```\n"
            "\n"
            "- `<NET>` is the **debug net name** (e.g. `SWD`), not a "
            "transport. Get it from `discover_bench()` or "
            "`lager debug --box <box-ip>`.\n"
            "- `<box-ip>` is the IP you connected to this MCP server on.\n"
            "- `-e path/to/app.elf` must be the **exact ELF that is flashed "
            "on the DUT** (same build). A mismatched ELF produces wrong or "
            "broken decodes — flash first, then stream.\n"
            "\n"
            "### Two gotchas that bite agents\n"
            "1. **Redirect stderr.** RTT payload goes to **stdout**; status "
            'lines ("JLinkGDBServer started!", etc.) go to **stderr**. Pipe '
            "stdout only — `2>/dev/null` (or `2>debug.log`) keeps status "
            "noise out of `defmt-print`'s input.\n"
            "2. **The stream never ends.** `--rtt` streams until the process "
            "is killed, which will hang a non-interactive agent forever. "
            "Bound it with `timeout` to capture a fixed window:\n"
            "\n"
            "```bash\n"
            "timeout 15 lager debug <NET> gdbserver --box <box-ip> --rtt 2>/dev/null \\\n"
            "  | defmt-print -e path/to/app.elf\n"
            "```\n"
            "\n"
            "When `timeout` kills the `lager` process the pipe closes and "
            "`defmt-print` exits cleanly on EOF.\n"
            "\n"
            "## Capturing the boot sequence\n"
            "Use `--rtt-reset` instead of `--rtt` to reset the DUT and then "
            "stream, so you catch logs emitted during early boot:\n"
            "\n"
            "```bash\n"
            "timeout 15 lager debug <NET> gdbserver --box <box-ip> --rtt-reset 2>/dev/null \\\n"
            "  | defmt-print -e build/app.elf\n"
            "```\n"
            "\n"
            "## Full flash → log loop\n"
            "```bash\n"
            "# 1. Flash the build under test\n"
            "lager debug <NET> flash --elf build/app.elf --box <box-ip>\n"
            "\n"
            "# 2. Reset + capture ~15s of defmt logs\n"
            "timeout 15 lager debug <NET> gdbserver --box <box-ip> --rtt-reset 2>/dev/null \\\n"
            "  | defmt-print -e build/app.elf\n"
            "```\n"
            "\n"
            "## Plain-text RTT (no defmt)\n"
            "Drop `defmt-print` entirely and read stdout directly:\n"
            "\n"
            "```bash\n"
            "timeout 15 lager debug <NET> gdbserver --box <box-ip> --rtt 2>/dev/null\n"
            "```\n"
            "\n"
            "## On-box decoding inside `lager python` (`rtt_defmt`)\n"
            "When you want decoded defmt logs **inside a test script** (e.g. "
            "to assert on them), use `dbg.rtt_defmt(elf=...)`. It opens the "
            "RTT channel, pipes it through `defmt-print` (which ships on the "
            "box), and yields **decoded text lines** — no manual subprocess "
            "wiring. The ELF is synced with your project and must match the "
            "flashed firmware.\n"
            "\n"
            "```python\n"
            "from lager import Net, NetType\n"
            "import time\n"
            "\n"
            'dbg = Net.get("SWD", type=NetType.Debug)\n'
            "\n"
            "# session() connects on entry (reusing a running gdbserver) and\n"
            "# tears it down on exit. Call flash/rtt_defmt/reset on `s` inside.\n"
            "lines = []\n"
            "with dbg.session() as s:\n"
            '    s.flash("build/app.elf")  # skip if already flashed\n'
            "\n"
            "    # Open the reader ONCE and keep it across the reset. It is\n"
            "    # reconnect-aware, so the flash/reset server bounce will not\n"
            "    # kill the stream.\n"
            '    with s.rtt_defmt(elf="build/app.elf", channel=0) as logs:\n'
            "        s.reset()  # restart to catch boot logs\n"
            "        deadline = time.time() + 10  # capture a bounded window\n"
            "        while time.time() < deadline:\n"
            "            line = logs.read_line(timeout=1.0)  # decoded str or None\n"
            "            if line:\n"
            "                print(line)\n"
            "                lines.append(line)\n"
            "```\n"
            "\n"
            "`rtt_defmt` exposes `read_line(timeout=None) -> str | None` and is "
            "iterable (`for line in logs: ...`). Like the CLI pipe, the stream "
            "never ends on its own — bound it with a time budget or a line "
            "count and then exit the `with` block.\n"
            "\n"
            "For **raw / plain-text** RTT (no defmt), use `dbg.rtt(channel=0)` "
            "and read `read_some(timeout=...)` bytes directly — but never "
            "`.decode()` defmt bytes that way.\n"
            "\n"
            "### You don't need flash/reset workarounds\n"
            "A flash (and a `reset()` via its probe grab) briefly bounces the "
            "gdbserver. You do **not** need to tear down and re-open your RTT "
            "reader around it, and you do **not** need your own retry loop:\n"
            "\n"
            "- **RTT is reconnect-aware** (both J-Link and OpenOCD): the reader "
            "transparently re-attaches to the same RTT port instead of going "
            "silent. Keep one `rtt_defmt`/`rtt` loop open across a flash+reset.\n"
            "- **reset()/erase()/read_memory() self-heal**: they retry with "
            "bounded backoff across the brief post-flash settling window, and "
            "only (re)start a server when one is genuinely down — a live server "
            "(and your attached RTT) is never disturbed.\n"
            "\n"
            "### DA1469x — the one exception\n"
            "On **DA1469x**, `flash()` deliberately leaves the gdbserver DOWN (it "
            "ends in a software reset, not a server restart). The self-heal will "
            "NOT auto-start it there, because an unhalted auto-start can return "
            "garbage QSPI-XIP reads. So on DA1469x you must reconnect explicitly "
            "after a flash before reset/read_memory:\n"
            "\n"
            "```python\n"
            "with dbg.session() as s:\n"
            '    s.flash("build/app.elf")\n'
            "    s.connect(ignore_if_connected=True)  # REQUIRED on DA1469x post-flash\n"
            "    s.reset()\n"
            "```\n"
            "\n"
            "RTT re-attach is still safe on DA1469x — it only resumes once the "
            "server is back up, it never starts one itself.\n"
            "\n"
            "### CLI pipe vs. rtt_defmt — which to use?\n"
            "- **Interactive / ad-hoc tailing, or you just want to eyeball "
            "logs** → CLI pipe.\n"
            "- **Programmatic: assert on log content, gate a test, combine "
            "with other net I/O in one script** → `rtt_defmt` in `lager "
            "python`.\n"
            "\n"
            "## Installing defmt-print\n"
            "`defmt-print` is preinstalled on the Lager box, so `rtt_defmt` "
            "works out of the box. For the **CLI pipe**, install it on your "
            "own machine with `cargo install defmt-print` (it must live where "
            "the `.elf` is). Version-match it to the firmware's `defmt` "
            "version if decodes look wrong.\n"
        )

    @mcp.resource("lager://guide/api-quick-reference")
    def guide_api_quick_reference() -> str:
        """Compact cheat sheet of the lager.Net API by NetType."""
        from ..data.api_reference import API_REFERENCE

        lines = [
            "# lager.Net API Quick Reference\n",
            "```python",
            "from lager import Net, NetType",
            "net = Net.get('name', type=NetType.X)",
            "```\n",
        ]

        for type_name, ref in sorted(API_REFERENCE.items()):
            lines.append(f"## {type_name}  (`{ref['net_type_enum']}`)")
            lines.append(f"```python\n{ref['get_pattern']}\n```")
            for m in ref["methods"]:
                lines.append(f"- `{m['sig']}` — {m['desc']}")
            lines.append("")

        return "\n".join(lines)
